type: google.api.Service
config_version: 3

http:
  rules:
    # environments
    #
    - selector: environments.EnvironmentsService.ListEnvironments
      get: /api/v2/environments

    # namespaces
    #
    - selector: environments.EnvironmentsService.GetNamespace
      get: /api/v2/environments/{environment_key}/namespaces/{key}

    - selector: environments.EnvironmentsService.ListNamespaces
      get: /api/v2/environments/{environment_key}/namespaces

    - selector: environments.EnvironmentsService.CreateNamespace
      post: /api/v2/environments/{environment_key}/namespaces
      body: "*"

    - selector: environments.EnvironmentsService.UpdateNamespace
      put: /api/v2/environments/{environment_key}/namespaces
      body: "*"

    - selector: environments.EnvironmentsService.DeleteNamespace
      delete: /api/v2/environments/{environment_key}/namespaces/{key}

    # resources
    #
    - selector: environments.EnvironmentsService.GetResource
      get: /api/v2/environments/{environment_key}/namespaces/{namespace_key}/resources/{type_url=*}/{key}

    - selector: environments.EnvironmentsService.ListResources
      get: /api/v2/environments/{environment_key}/namespaces/{namespace_key}/resources/{type_url=*}

    - selector: environments.EnvironmentsService.CreateResource
      post: /api/v2/environments/{environment_key}/namespaces/{namespace_key}/resources
      body: "*"

    - selector: environments.EnvironmentsService.UpdateResource
      put: /api/v2/environments/{environment_key}/namespaces/{namespace_key}/resources
      body: "*"

    - selector: environments.EnvironmentsService.DeleteResource
      delete: /api/v2/environments/{environment_key}/namespaces/{namespace_key}/resources/{type_url=*}/{key}
