// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: environments.proto

package environments

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Environment struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Key           string                    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Default       *bool                     `protobuf:"varint,3,opt,name=default,proto3,oneof" json:"default,omitempty"`
	Configuration *EnvironmentConfiguration `protobuf:"bytes,4,opt,name=configuration,proto3,oneof" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_environments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{0}
}

func (x *Environment) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Environment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Environment) GetDefault() bool {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return false
}

func (x *Environment) GetConfiguration() *EnvironmentConfiguration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type EnvironmentConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Remote        string                 `protobuf:"bytes,1,opt,name=remote,proto3" json:"remote,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Directory     string                 `protobuf:"bytes,3,opt,name=directory,proto3" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentConfiguration) Reset() {
	*x = EnvironmentConfiguration{}
	mi := &file_environments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentConfiguration) ProtoMessage() {}

func (x *EnvironmentConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentConfiguration.ProtoReflect.Descriptor instead.
func (*EnvironmentConfiguration) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{1}
}

func (x *EnvironmentConfiguration) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *EnvironmentConfiguration) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *EnvironmentConfiguration) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

type ListEnvironmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnvironmentsRequest) Reset() {
	*x = ListEnvironmentsRequest{}
	mi := &file_environments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnvironmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnvironmentsRequest) ProtoMessage() {}

func (x *ListEnvironmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnvironmentsRequest.ProtoReflect.Descriptor instead.
func (*ListEnvironmentsRequest) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{2}
}

type ListEnvironmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environments  []*Environment         `protobuf:"bytes,1,rep,name=environments,proto3" json:"environments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnvironmentsResponse) Reset() {
	*x = ListEnvironmentsResponse{}
	mi := &file_environments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnvironmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnvironmentsResponse) ProtoMessage() {}

func (x *ListEnvironmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnvironmentsResponse.ProtoReflect.Descriptor instead.
func (*ListEnvironmentsResponse) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{3}
}

func (x *ListEnvironmentsResponse) GetEnvironments() []*Environment {
	if x != nil {
		return x.Environments
	}
	return nil
}

type Namespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Protected     *bool                  `protobuf:"varint,4,opt,name=protected,proto3,oneof" json:"protected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_environments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{4}
}

func (x *Namespace) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Namespace) GetProtected() bool {
	if x != nil && x.Protected != nil {
		return *x.Protected
	}
	return false
}

type GetNamespaceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentKey string                 `protobuf:"bytes,1,opt,name=environment_key,json=environmentKey,proto3" json:"environment_key,omitempty"`
	Key            string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNamespaceRequest) Reset() {
	*x = GetNamespaceRequest{}
	mi := &file_environments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceRequest) ProtoMessage() {}

func (x *GetNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceRequest.ProtoReflect.Descriptor instead.
func (*GetNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{5}
}

func (x *GetNamespaceRequest) GetEnvironmentKey() string {
	if x != nil {
		return x.EnvironmentKey
	}
	return ""
}

func (x *GetNamespaceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type NamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *Namespace             `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Revision      string                 `protobuf:"bytes,100,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceResponse) Reset() {
	*x = NamespaceResponse{}
	mi := &file_environments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceResponse) ProtoMessage() {}

func (x *NamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceResponse.ProtoReflect.Descriptor instead.
func (*NamespaceResponse) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{6}
}

func (x *NamespaceResponse) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *NamespaceResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type ListNamespacesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentKey string                 `protobuf:"bytes,1,opt,name=environment_key,json=environmentKey,proto3" json:"environment_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListNamespacesRequest) Reset() {
	*x = ListNamespacesRequest{}
	mi := &file_environments_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesRequest) ProtoMessage() {}

func (x *ListNamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesRequest.ProtoReflect.Descriptor instead.
func (*ListNamespacesRequest) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{7}
}

func (x *ListNamespacesRequest) GetEnvironmentKey() string {
	if x != nil {
		return x.EnvironmentKey
	}
	return ""
}

type ListNamespacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Namespace           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Revision      string                 `protobuf:"bytes,100,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesResponse) Reset() {
	*x = ListNamespacesResponse{}
	mi := &file_environments_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesResponse) ProtoMessage() {}

func (x *ListNamespacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesResponse.ProtoReflect.Descriptor instead.
func (*ListNamespacesResponse) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{8}
}

func (x *ListNamespacesResponse) GetItems() []*Namespace {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListNamespacesResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type UpdateNamespaceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentKey string                 `protobuf:"bytes,1,opt,name=environment_key,json=environmentKey,proto3" json:"environment_key,omitempty"`
	Key            string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Protected      *bool                  `protobuf:"varint,5,opt,name=protected,proto3,oneof" json:"protected,omitempty"`
	Revision       string                 `protobuf:"bytes,100,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateNamespaceRequest) Reset() {
	*x = UpdateNamespaceRequest{}
	mi := &file_environments_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNamespaceRequest) ProtoMessage() {}

func (x *UpdateNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNamespaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateNamespaceRequest) GetEnvironmentKey() string {
	if x != nil {
		return x.EnvironmentKey
	}
	return ""
}

func (x *UpdateNamespaceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateNamespaceRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateNamespaceRequest) GetProtected() bool {
	if x != nil && x.Protected != nil {
		return *x.Protected
	}
	return false
}

func (x *UpdateNamespaceRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type DeleteNamespaceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentKey string                 `protobuf:"bytes,1,opt,name=environment_key,json=environmentKey,proto3" json:"environment_key,omitempty"`
	Key            string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Revision       string                 `protobuf:"bytes,100,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteNamespaceRequest) Reset() {
	*x = DeleteNamespaceRequest{}
	mi := &file_environments_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNamespaceRequest) ProtoMessage() {}

func (x *DeleteNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNamespaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteNamespaceRequest) GetEnvironmentKey() string {
	if x != nil {
		return x.EnvironmentKey
	}
	return ""
}

func (x *DeleteNamespaceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteNamespaceRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type DeleteNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      string                 `protobuf:"bytes,100,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNamespaceResponse) Reset() {
	*x = DeleteNamespaceResponse{}
	mi := &file_environments_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNamespaceResponse) ProtoMessage() {}

func (x *DeleteNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNamespaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteNamespaceResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type GetResourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentKey string                 `protobuf:"bytes,1,opt,name=environment_key,json=environmentKey,proto3" json:"environment_key,omitempty"`
	NamespaceKey   string                 `protobuf:"bytes,2,opt,name=namespace_key,json=namespaceKey,proto3" json:"namespace_key,omitempty"`
	TypeUrl        string                 `protobuf:"bytes,3,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Key            string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_environments_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{12}
}

func (x *GetResourceRequest) GetEnvironmentKey() string {
	if x != nil {
		return x.EnvironmentKey
	}
	return ""
}

func (x *GetResourceRequest) GetNamespaceKey() string {
	if x != nil {
		return x.NamespaceKey
	}
	return ""
}

func (x *GetResourceRequest) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *GetResourceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamespaceKey  string                 `protobuf:"bytes,1,opt,name=namespace_key,json=namespaceKey,proto3" json:"namespace_key,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_environments_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{13}
}

func (x *Resource) GetNamespaceKey() string {
	if x != nil {
		return x.NamespaceKey
	}
	return ""
}

func (x *Resource) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Resource) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Revision      string                 `protobuf:"bytes,100,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceResponse) Reset() {
	*x = ResourceResponse{}
	mi := &file_environments_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceResponse) ProtoMessage() {}

func (x *ResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceResponse.ProtoReflect.Descriptor instead.
func (*ResourceResponse) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{14}
}

func (x *ResourceResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ResourceResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type ListResourcesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentKey string                 `protobuf:"bytes,1,opt,name=environment_key,json=environmentKey,proto3" json:"environment_key,omitempty"`
	NamespaceKey   string                 `protobuf:"bytes,2,opt,name=namespace_key,json=namespaceKey,proto3" json:"namespace_key,omitempty"`
	TypeUrl        string                 `protobuf:"bytes,3,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_environments_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{15}
}

func (x *ListResourcesRequest) GetEnvironmentKey() string {
	if x != nil {
		return x.EnvironmentKey
	}
	return ""
}

func (x *ListResourcesRequest) GetNamespaceKey() string {
	if x != nil {
		return x.NamespaceKey
	}
	return ""
}

func (x *ListResourcesRequest) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	Revision      string                 `protobuf:"bytes,100,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_environments_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{16}
}

func (x *ListResourcesResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ListResourcesResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type UpdateResourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentKey string                 `protobuf:"bytes,1,opt,name=environment_key,json=environmentKey,proto3" json:"environment_key,omitempty"`
	NamespaceKey   string                 `protobuf:"bytes,2,opt,name=namespace_key,json=namespaceKey,proto3" json:"namespace_key,omitempty"`
	Key            string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Payload        *anypb.Any             `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Revision       string                 `protobuf:"bytes,100,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateResourceRequest) Reset() {
	*x = UpdateResourceRequest{}
	mi := &file_environments_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceRequest) ProtoMessage() {}

func (x *UpdateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateResourceRequest) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateResourceRequest) GetEnvironmentKey() string {
	if x != nil {
		return x.EnvironmentKey
	}
	return ""
}

func (x *UpdateResourceRequest) GetNamespaceKey() string {
	if x != nil {
		return x.NamespaceKey
	}
	return ""
}

func (x *UpdateResourceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateResourceRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateResourceRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type DeleteResourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is the fully-qualified protobuf message name
	EnvironmentKey string `protobuf:"bytes,1,opt,name=environment_key,json=environmentKey,proto3" json:"environment_key,omitempty"`
	NamespaceKey   string `protobuf:"bytes,2,opt,name=namespace_key,json=namespaceKey,proto3" json:"namespace_key,omitempty"`
	TypeUrl        string `protobuf:"bytes,3,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Key            string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Revision       string `protobuf:"bytes,100,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_environments_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteResourceRequest) GetEnvironmentKey() string {
	if x != nil {
		return x.EnvironmentKey
	}
	return ""
}

func (x *DeleteResourceRequest) GetNamespaceKey() string {
	if x != nil {
		return x.NamespaceKey
	}
	return ""
}

func (x *DeleteResourceRequest) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *DeleteResourceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteResourceRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type DeleteResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      string                 `protobuf:"bytes,100,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceResponse) Reset() {
	*x = DeleteResourceResponse{}
	mi := &file_environments_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceResponse) ProtoMessage() {}

func (x *DeleteResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_environments_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceResponse) Descriptor() ([]byte, []int) {
	return file_environments_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteResourceResponse) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

var File_environments_proto protoreflect.FileDescriptor

const file_environments_proto_rawDesc = "" +
	"\n" +
	"\x12environments.proto\x12\fenvironments\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/protobuf/any.proto\"\xc3\x01\n" +
	"\vEnvironment\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\adefault\x18\x03 \x01(\bH\x00R\adefault\x88\x01\x01\x12Q\n" +
	"\rconfiguration\x18\x04 \x01(\v2&.environments.EnvironmentConfigurationH\x01R\rconfiguration\x88\x01\x01B\n" +
	"\n" +
	"\b_defaultB\x10\n" +
	"\x0e_configuration\"h\n" +
	"\x18EnvironmentConfiguration\x12\x16\n" +
	"\x06remote\x18\x01 \x01(\tR\x06remote\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x1c\n" +
	"\tdirectory\x18\x03 \x01(\tR\tdirectory\"\x19\n" +
	"\x17ListEnvironmentsRequest\"Y\n" +
	"\x18ListEnvironmentsResponse\x12=\n" +
	"\fenvironments\x18\x01 \x03(\v2\x19.environments.EnvironmentR\fenvironments\"\x99\x01\n" +
	"\tNamespace\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12!\n" +
	"\tprotected\x18\x04 \x01(\bH\x01R\tprotected\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_protected\"P\n" +
	"\x13GetNamespaceRequest\x12'\n" +
	"\x0fenvironment_key\x18\x01 \x01(\tR\x0eenvironmentKey\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"f\n" +
	"\x11NamespaceResponse\x125\n" +
	"\tnamespace\x18\x01 \x01(\v2\x17.environments.NamespaceR\tnamespace\x12\x1a\n" +
	"\brevision\x18d \x01(\tR\brevision\"@\n" +
	"\x15ListNamespacesRequest\x12'\n" +
	"\x0fenvironment_key\x18\x01 \x01(\tR\x0eenvironmentKey\"c\n" +
	"\x16ListNamespacesResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.environments.NamespaceR\x05items\x12\x1a\n" +
	"\brevision\x18d \x01(\tR\brevision\"\xeb\x01\n" +
	"\x16UpdateNamespaceRequest\x12'\n" +
	"\x0fenvironment_key\x18\x01 \x01(\tR\x0eenvironmentKey\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12!\n" +
	"\tprotected\x18\x05 \x01(\bH\x01R\tprotected\x88\x01\x01\x12\x1a\n" +
	"\brevision\x18d \x01(\tR\brevisionB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_protected\"o\n" +
	"\x16DeleteNamespaceRequest\x12'\n" +
	"\x0fenvironment_key\x18\x01 \x01(\tR\x0eenvironmentKey\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1a\n" +
	"\brevision\x18d \x01(\tR\brevision\"5\n" +
	"\x17DeleteNamespaceResponse\x12\x1a\n" +
	"\brevision\x18d \x01(\tR\brevision\"\x8f\x01\n" +
	"\x12GetResourceRequest\x12'\n" +
	"\x0fenvironment_key\x18\x01 \x01(\tR\x0eenvironmentKey\x12#\n" +
	"\rnamespace_key\x18\x02 \x01(\tR\fnamespaceKey\x12\x19\n" +
	"\btype_url\x18\x03 \x01(\tR\atypeUrl\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\"q\n" +
	"\bResource\x12#\n" +
	"\rnamespace_key\x18\x01 \x01(\tR\fnamespaceKey\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12.\n" +
	"\apayload\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\apayload\"b\n" +
	"\x10ResourceResponse\x122\n" +
	"\bresource\x18\x01 \x01(\v2\x16.environments.ResourceR\bresource\x12\x1a\n" +
	"\brevision\x18d \x01(\tR\brevision\"\x7f\n" +
	"\x14ListResourcesRequest\x12'\n" +
	"\x0fenvironment_key\x18\x01 \x01(\tR\x0eenvironmentKey\x12#\n" +
	"\rnamespace_key\x18\x02 \x01(\tR\fnamespaceKey\x12\x19\n" +
	"\btype_url\x18\x03 \x01(\tR\atypeUrl\"i\n" +
	"\x15ListResourcesResponse\x124\n" +
	"\tresources\x18\x01 \x03(\v2\x16.environments.ResourceR\tresources\x12\x1a\n" +
	"\brevision\x18d \x01(\tR\brevision\"\xc3\x01\n" +
	"\x15UpdateResourceRequest\x12'\n" +
	"\x0fenvironment_key\x18\x01 \x01(\tR\x0eenvironmentKey\x12#\n" +
	"\rnamespace_key\x18\x02 \x01(\tR\fnamespaceKey\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12.\n" +
	"\apayload\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\apayload\x12\x1a\n" +
	"\brevision\x18d \x01(\tR\brevision\"\xae\x01\n" +
	"\x15DeleteResourceRequest\x12'\n" +
	"\x0fenvironment_key\x18\x01 \x01(\tR\x0eenvironmentKey\x12#\n" +
	"\rnamespace_key\x18\x02 \x01(\tR\fnamespaceKey\x12\x19\n" +
	"\btype_url\x18\x03 \x01(\tR\atypeUrl\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x1a\n" +
	"\brevision\x18d \x01(\tR\brevision\"4\n" +
	"\x16DeleteResourceResponse\x12\x1a\n" +
	"\brevision\x18d \x01(\tR\brevision2\x87\x10\n" +
	"\x13EnvironmentsService\x12\x94\x01\n" +
	"\x10ListEnvironments\x12%.environments.ListEnvironmentsRequest\x1a&.environments.ListEnvironmentsResponse\"1\xbaG\x12*\x10listEnvironments\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v2/environments\x12\xa4\x01\n" +
	"\fGetNamespace\x12!.environments.GetNamespaceRequest\x1a\x1f.environments.NamespaceResponse\"P\xbaG\x0e*\fgetNamespace\x82\xd3\xe4\x93\x029\x127/api/v2/environments/{environment_key}/namespaces/{key}\x12\xa9\x01\n" +
	"\x0eListNamespaces\x12#.environments.ListNamespacesRequest\x1a$.environments.ListNamespacesResponse\"L\xbaG\x10*\x0elistNamespaces\x82\xd3\xe4\x93\x023\x121/api/v2/environments/{environment_key}/namespaces\x12\xaa\x01\n" +
	"\x0fCreateNamespace\x12$.environments.UpdateNamespaceRequest\x1a\x1f.environments.NamespaceResponse\"P\xbaG\x11*\x0fcreateNamespace\x82\xd3\xe4\x93\x026:\x01*\"1/api/v2/environments/{environment_key}/namespaces\x12\xaa\x01\n" +
	"\x0fUpdateNamespace\x12$.environments.UpdateNamespaceRequest\x1a\x1f.environments.NamespaceResponse\"P\xbaG\x11*\x0fupdateNamespace\x82\xd3\xe4\x93\x026:\x01*\x1a1/api/v2/environments/{environment_key}/namespaces\x12\xb3\x01\n" +
	"\x0fDeleteNamespace\x12$.environments.DeleteNamespaceRequest\x1a%.environments.DeleteNamespaceResponse\"S\xbaG\x11*\x0fdeleteNamespace\x82\xd3\xe4\x93\x029*7/api/v2/environments/{environment_key}/namespaces/{key}\x12\xc7\x01\n" +
	"\vGetResource\x12 .environments.GetResourceRequest\x1a\x1e.environments.ResourceResponse\"v\xbaG\r*\vgetResource\x82\xd3\xe4\x93\x02`\x12^/api/v2/environments/{environment_key}/namespaces/{namespace_key}/resources/{type_url=*}/{key}\x12\xcc\x01\n" +
	"\rListResources\x12\".environments.ListResourcesRequest\x1a#.environments.ListResourcesResponse\"r\xbaG\x0f*\rlistResources\x82\xd3\xe4\x93\x02Z\x12X/api/v2/environments/{environment_key}/namespaces/{namespace_key}/resources/{type_url=*}\x12\xc0\x01\n" +
	"\x0eCreateResource\x12#.environments.UpdateResourceRequest\x1a\x1e.environments.ResourceResponse\"i\xbaG\x10*\x0ecreateResource\x82\xd3\xe4\x93\x02P:\x01*\"K/api/v2/environments/{environment_key}/namespaces/{namespace_key}/resources\x12\xc0\x01\n" +
	"\x0eUpdateResource\x12#.environments.UpdateResourceRequest\x1a\x1e.environments.ResourceResponse\"i\xbaG\x10*\x0eupdateResource\x82\xd3\xe4\x93\x02P:\x01*\x1aK/api/v2/environments/{environment_key}/namespaces/{namespace_key}/resources\x12\xd6\x01\n" +
	"\x0eDeleteResource\x12#.environments.DeleteResourceRequest\x1a$.environments.DeleteResourceResponse\"y\xbaG\x10*\x0edeleteResource\x82\xd3\xe4\x93\x02`*^/api/v2/environments/{environment_key}/namespaces/{namespace_key}/resources/{type_url=*}/{key}B'Z%go.flipt.io/flipt/rpc/v2/environmentsb\x06proto3"

var (
	file_environments_proto_rawDescOnce sync.Once
	file_environments_proto_rawDescData []byte
)

func file_environments_proto_rawDescGZIP() []byte {
	file_environments_proto_rawDescOnce.Do(func() {
		file_environments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_environments_proto_rawDesc), len(file_environments_proto_rawDesc)))
	})
	return file_environments_proto_rawDescData
}

var file_environments_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_environments_proto_goTypes = []any{
	(*Environment)(nil),              // 0: environments.Environment
	(*EnvironmentConfiguration)(nil), // 1: environments.EnvironmentConfiguration
	(*ListEnvironmentsRequest)(nil),  // 2: environments.ListEnvironmentsRequest
	(*ListEnvironmentsResponse)(nil), // 3: environments.ListEnvironmentsResponse
	(*Namespace)(nil),                // 4: environments.Namespace
	(*GetNamespaceRequest)(nil),      // 5: environments.GetNamespaceRequest
	(*NamespaceResponse)(nil),        // 6: environments.NamespaceResponse
	(*ListNamespacesRequest)(nil),    // 7: environments.ListNamespacesRequest
	(*ListNamespacesResponse)(nil),   // 8: environments.ListNamespacesResponse
	(*UpdateNamespaceRequest)(nil),   // 9: environments.UpdateNamespaceRequest
	(*DeleteNamespaceRequest)(nil),   // 10: environments.DeleteNamespaceRequest
	(*DeleteNamespaceResponse)(nil),  // 11: environments.DeleteNamespaceResponse
	(*GetResourceRequest)(nil),       // 12: environments.GetResourceRequest
	(*Resource)(nil),                 // 13: environments.Resource
	(*ResourceResponse)(nil),         // 14: environments.ResourceResponse
	(*ListResourcesRequest)(nil),     // 15: environments.ListResourcesRequest
	(*ListResourcesResponse)(nil),    // 16: environments.ListResourcesResponse
	(*UpdateResourceRequest)(nil),    // 17: environments.UpdateResourceRequest
	(*DeleteResourceRequest)(nil),    // 18: environments.DeleteResourceRequest
	(*DeleteResourceResponse)(nil),   // 19: environments.DeleteResourceResponse
	(*anypb.Any)(nil),                // 20: google.protobuf.Any
}
var file_environments_proto_depIdxs = []int32{
	1,  // 0: environments.Environment.configuration:type_name -> environments.EnvironmentConfiguration
	0,  // 1: environments.ListEnvironmentsResponse.environments:type_name -> environments.Environment
	4,  // 2: environments.NamespaceResponse.namespace:type_name -> environments.Namespace
	4,  // 3: environments.ListNamespacesResponse.items:type_name -> environments.Namespace
	20, // 4: environments.Resource.payload:type_name -> google.protobuf.Any
	13, // 5: environments.ResourceResponse.resource:type_name -> environments.Resource
	13, // 6: environments.ListResourcesResponse.resources:type_name -> environments.Resource
	20, // 7: environments.UpdateResourceRequest.payload:type_name -> google.protobuf.Any
	2,  // 8: environments.EnvironmentsService.ListEnvironments:input_type -> environments.ListEnvironmentsRequest
	5,  // 9: environments.EnvironmentsService.GetNamespace:input_type -> environments.GetNamespaceRequest
	7,  // 10: environments.EnvironmentsService.ListNamespaces:input_type -> environments.ListNamespacesRequest
	9,  // 11: environments.EnvironmentsService.CreateNamespace:input_type -> environments.UpdateNamespaceRequest
	9,  // 12: environments.EnvironmentsService.UpdateNamespace:input_type -> environments.UpdateNamespaceRequest
	10, // 13: environments.EnvironmentsService.DeleteNamespace:input_type -> environments.DeleteNamespaceRequest
	12, // 14: environments.EnvironmentsService.GetResource:input_type -> environments.GetResourceRequest
	15, // 15: environments.EnvironmentsService.ListResources:input_type -> environments.ListResourcesRequest
	17, // 16: environments.EnvironmentsService.CreateResource:input_type -> environments.UpdateResourceRequest
	17, // 17: environments.EnvironmentsService.UpdateResource:input_type -> environments.UpdateResourceRequest
	18, // 18: environments.EnvironmentsService.DeleteResource:input_type -> environments.DeleteResourceRequest
	3,  // 19: environments.EnvironmentsService.ListEnvironments:output_type -> environments.ListEnvironmentsResponse
	6,  // 20: environments.EnvironmentsService.GetNamespace:output_type -> environments.NamespaceResponse
	8,  // 21: environments.EnvironmentsService.ListNamespaces:output_type -> environments.ListNamespacesResponse
	6,  // 22: environments.EnvironmentsService.CreateNamespace:output_type -> environments.NamespaceResponse
	6,  // 23: environments.EnvironmentsService.UpdateNamespace:output_type -> environments.NamespaceResponse
	11, // 24: environments.EnvironmentsService.DeleteNamespace:output_type -> environments.DeleteNamespaceResponse
	14, // 25: environments.EnvironmentsService.GetResource:output_type -> environments.ResourceResponse
	16, // 26: environments.EnvironmentsService.ListResources:output_type -> environments.ListResourcesResponse
	14, // 27: environments.EnvironmentsService.CreateResource:output_type -> environments.ResourceResponse
	14, // 28: environments.EnvironmentsService.UpdateResource:output_type -> environments.ResourceResponse
	19, // 29: environments.EnvironmentsService.DeleteResource:output_type -> environments.DeleteResourceResponse
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_environments_proto_init() }
func file_environments_proto_init() {
	if File_environments_proto != nil {
		return
	}
	file_environments_proto_msgTypes[0].OneofWrappers = []any{}
	file_environments_proto_msgTypes[4].OneofWrappers = []any{}
	file_environments_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_environments_proto_rawDesc), len(file_environments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_environments_proto_goTypes,
		DependencyIndexes: file_environments_proto_depIdxs,
		MessageInfos:      file_environments_proto_msgTypes,
	}.Build()
	File_environments_proto = out.File
	file_environments_proto_goTypes = nil
	file_environments_proto_depIdxs = nil
}
