source "https://rubygems.org"

# Specify your gem's dependencies in flipt-client-ruby.gemspec
gemspec

gem "rake", "~> 12.0"
gem "ffi", "~> 1.16"

group :development do
  gem "bundler", "~> 2.0"
  gem "rspec", "~> 3.0"
end