apiVersion: v2
name: flipt
home: https://flipt.io
description: Flipt is an open source, self-hosted feature flag solution for your existing infrastructure.
type: application
version: 0.2.0
appVersion: "v1.8.3"
