#!/bin/bash

cd "$(dirname "$0")/../.." || exit

run()
{
    # run any pending db migrations
    ./bin/flipt migrate --config ./config/local.yml &> /dev/null

    ./bin/flipt --config ./config/local.yml &> "${GITHUB_WORKSPACE}/artifacts/flipt.log" &

    flipt_host="0.0.0.0:8080"

    sleep 5

    echo -e "\e[32m                \e[0m"
    echo -e "\e[32m===========================================\e[0m"
    echo -e "\e[32mStart UI testing $flipt_host\e[0m"
    echo -e "\e[32m===========================================\e[0m"

    ./script/test/helpers/wait-for-it/wait-for-it.sh "$flipt_host" -t 30

    cd "ui" && yarn && yarn qawolf test --headless
}

run