version: "3"

services:
  flipt:
    image: flipt/flipt:latest
    command: ["./flipt", "--force-migrate"]
    ports:
      - "8080:8080"
    environment:
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_AUDIT_SINKS_WEBHOOK_ENABLED=true
      - FLIPT_AUDIT_EVENTS=flag:created flag:updated
      - FLIPT_AUDIT_SINKS_WEBHOOK_URL=http://webhook:8081/
      - FLIPT_META_TELEMETRY_ENABLED=false
    networks:
      - flipt_network

  webhook:
    build: .
    networks:
      - flipt_network

networks:
  flipt_network:
