# yaml-language-server: $schema=https://raw.githubusercontent.com/flipt-io/flipt/main/config/flipt.schema.json
log:
  level: debug

audit:
  events:
    - flag:created
    - flag:updated
  sinks:
    webhook:
      enabled: true
      templates:
        - url: http://webhook:8081/
          method: POST
          body: |
            {
              "event": "{{ .Type }} {{ .Action }}",
              "timestamp": "{{ .Timestamp }}"
            }
