messages:
  - role: system
    content: |
      You are a changelog validator that ensures release documentation is complete and accurate.
      You analyze git commits and existing changelog entries to identify missing items and suggest improvements.

      Your task is to:
      1. Check if a changelog entry exists for the given version
      2. Compare commits since last release with changelog content
      3. Identify any missing significant changes
      4. Verify proper categorization (Added, Fixed, Changed, Deprecated, Removed, Security)
      5. Check for proper formatting and consistency

      Output a JSON response with the validation results.

  - role: user
    content: |
      Validate the changelog for version {{version}}.

      Current CHANGELOG.md content:
      ```
      {{changelog_content}}
      ```

      Commits since {{previous_version}}:
      ```
      {{commits}}
      ```

      Pull requests merged since last release:
      ```
      {{pull_requests}}
      ```

      Validate completeness and suggest any missing items.

model: openai/gpt-4o

response_format:
  type: json_object
  json_schema:
    name: changelog_validation
    schema:
      type: object
      properties:
        version_exists:
          type: boolean
          description: Whether an entry for this version exists in the changelog
        is_complete:
          type: boolean
          description: Whether the changelog appears complete based on commits
        missing_items:
          type: array
          items:
            type: object
            properties:
              commit:
                type: string
                description: Commit SHA or PR number
              description:
                type: string
                description: What appears to be missing
              category:
                type: string
                enum:
                  [
                    "Added",
                    "Fixed",
                    "Changed",
                    "Deprecated",
                    "Removed",
                    "Security",
                    "Dependencies",
                  ]
                description: Suggested category for this item
        formatting_issues:
          type: array
          items:
            type: string
            description: Any formatting or consistency issues found
        suggestions:
          type: string
          description: Additional suggestions for improving the changelog
      required:
        [
          "version_exists",
          "is_complete",
          "missing_items",
          "formatting_issues",
          "suggestions",
        ]
