// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sql

import (
	"context"
	"database/sql/driver"

	mock "github.com/stretchr/testify/mock"
)

// newMockdriverContext creates a new instance of mockdriverContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdriverContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdriverContext {
	mock := &mockdriverContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdriverContext is an autogenerated mock type for the driverContext type
type mockdriverContext struct {
	mock.Mock
}

type mockdriverContext_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdriverContext) EXPECT() *mockdriverContext_Expecter {
	return &mockdriverContext_Expecter{mock: &_m.Mock}
}

// OpenConnector provides a mock function for the type mockdriverContext
func (_mock *mockdriverContext) OpenConnector(name string) (driver.Connector, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for OpenConnector")
	}

	var r0 driver.Connector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (driver.Connector, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) driver.Connector); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Connector)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdriverContext_OpenConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenConnector'
type mockdriverContext_OpenConnector_Call struct {
	*mock.Call
}

// OpenConnector is a helper method to define mock.On call
//   - name string
func (_e *mockdriverContext_Expecter) OpenConnector(name interface{}) *mockdriverContext_OpenConnector_Call {
	return &mockdriverContext_OpenConnector_Call{Call: _e.mock.On("OpenConnector", name)}
}

func (_c *mockdriverContext_OpenConnector_Call) Run(run func(name string)) *mockdriverContext_OpenConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdriverContext_OpenConnector_Call) Return(connector driver.Connector, err error) *mockdriverContext_OpenConnector_Call {
	_c.Call.Return(connector, err)
	return _c
}

func (_c *mockdriverContext_OpenConnector_Call) RunAndReturn(run func(name string) (driver.Connector, error)) *mockdriverContext_OpenConnector_Call {
	_c.Call.Return(run)
	return _c
}

// newMockdriverConn creates a new instance of mockdriverConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockdriverConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockdriverConn {
	mock := &mockdriverConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockdriverConn is an autogenerated mock type for the driverConn type
type mockdriverConn struct {
	mock.Mock
}

type mockdriverConn_Expecter struct {
	mock *mock.Mock
}

func (_m *mockdriverConn) EXPECT() *mockdriverConn_Expecter {
	return &mockdriverConn_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type mockdriverConn
func (_mock *mockdriverConn) Begin() (driver.Tx, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 driver.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (driver.Tx, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() driver.Tx); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdriverConn_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type mockdriverConn_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
func (_e *mockdriverConn_Expecter) Begin() *mockdriverConn_Begin_Call {
	return &mockdriverConn_Begin_Call{Call: _e.mock.On("Begin")}
}

func (_c *mockdriverConn_Begin_Call) Run(run func()) *mockdriverConn_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockdriverConn_Begin_Call) Return(tx driver.Tx, err error) *mockdriverConn_Begin_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *mockdriverConn_Begin_Call) RunAndReturn(run func() (driver.Tx, error)) *mockdriverConn_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type mockdriverConn
func (_mock *mockdriverConn) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockdriverConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockdriverConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *mockdriverConn_Expecter) Close() *mockdriverConn_Close_Call {
	return &mockdriverConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *mockdriverConn_Close_Call) Run(run func()) *mockdriverConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockdriverConn_Close_Call) Return(err error) *mockdriverConn_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockdriverConn_Close_Call) RunAndReturn(run func() error) *mockdriverConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function for the type mockdriverConn
func (_mock *mockdriverConn) Connect(context1 context.Context) (driver.Conn, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 driver.Conn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (driver.Conn, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) driver.Conn); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdriverConn_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type mockdriverConn_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - context1 context.Context
func (_e *mockdriverConn_Expecter) Connect(context1 interface{}) *mockdriverConn_Connect_Call {
	return &mockdriverConn_Connect_Call{Call: _e.mock.On("Connect", context1)}
}

func (_c *mockdriverConn_Connect_Call) Run(run func(context1 context.Context)) *mockdriverConn_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdriverConn_Connect_Call) Return(conn driver.Conn, err error) *mockdriverConn_Connect_Call {
	_c.Call.Return(conn, err)
	return _c
}

func (_c *mockdriverConn_Connect_Call) RunAndReturn(run func(context1 context.Context) (driver.Conn, error)) *mockdriverConn_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Driver provides a mock function for the type mockdriverConn
func (_mock *mockdriverConn) Driver() driver.Driver {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Driver")
	}

	var r0 driver.Driver
	if returnFunc, ok := ret.Get(0).(func() driver.Driver); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Driver)
		}
	}
	return r0
}

// mockdriverConn_Driver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Driver'
type mockdriverConn_Driver_Call struct {
	*mock.Call
}

// Driver is a helper method to define mock.On call
func (_e *mockdriverConn_Expecter) Driver() *mockdriverConn_Driver_Call {
	return &mockdriverConn_Driver_Call{Call: _e.mock.On("Driver")}
}

func (_c *mockdriverConn_Driver_Call) Run(run func()) *mockdriverConn_Driver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockdriverConn_Driver_Call) Return(driver1 driver.Driver) *mockdriverConn_Driver_Call {
	_c.Call.Return(driver1)
	return _c
}

func (_c *mockdriverConn_Driver_Call) RunAndReturn(run func() driver.Driver) *mockdriverConn_Driver_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function for the type mockdriverConn
func (_mock *mockdriverConn) Prepare(query string) (driver.Stmt, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 driver.Stmt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (driver.Stmt, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(string) driver.Stmt); ok {
		r0 = returnFunc(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Stmt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockdriverConn_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type mockdriverConn_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - query string
func (_e *mockdriverConn_Expecter) Prepare(query interface{}) *mockdriverConn_Prepare_Call {
	return &mockdriverConn_Prepare_Call{Call: _e.mock.On("Prepare", query)}
}

func (_c *mockdriverConn_Prepare_Call) Run(run func(query string)) *mockdriverConn_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockdriverConn_Prepare_Call) Return(stmt driver.Stmt, err error) *mockdriverConn_Prepare_Call {
	_c.Call.Return(stmt, err)
	return _c
}

func (_c *mockdriverConn_Prepare_Call) RunAndReturn(run func(query string) (driver.Stmt, error)) *mockdriverConn_Prepare_Call {
	_c.Call.Return(run)
	return _c
}
