# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2

project_name: flipt

git:
  tag_sort: semver

monorepo:
  tag_prefix: v

builds:
  - builder: prebuilt
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    prebuilt:
      path: tmp/dist/flipt_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}{{ with .Arm64 }}_{{ . }}{{ end }}/flipt
    binary: flipt

sboms:
  - artifacts: archive

archives:
  - id: main
    name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto # enable rc releases (e.g. v1.0.0-rc.1)
  target_commitish: "{{ .Commit }}"
  footer: |
    ## Installation
    ### Docker Images :whale:
    ```bash
      docker pull docker.flipt.io/flipt/flipt:v{{ .Tag }}
    ```
    ```bash
      docker pull ghcr.io/flipt-io/flipt:v{{ .Tag }}
    ```
    ## Thank you!
    We hope you :heart: this release! Feel free to open issues/discussions or reach out to us on Discord if you have any questions or feedback.
    - [Discord](https://flipt.io/discord)
    - [Github Discussions](https://github.com/flipt-io/flipt/discussions)
    - [Github Issues](https://github.com/flipt-io/flipt/issues)
    - [Website](https://flipt.io)

snapshot:
  version_template: "v2-{{ .ShortCommit }}-snapshot"

nightly:
  # Default is `{{ incpatch .Version }}-{{ .ShortCommit }}-nightly`.
  version_template: "{{ incpatch .Version }}-nightly"

changelog:
  disable: true
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  sort: asc
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Dependencies"
      regexp: '^.*?deps(\([[:word:]]+\))??!?:.+$'
      order: 999
    - title: "Other"
      order: 3

dockers:
  - dockerfile: ./build/Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "flipt/flipt:v{{ .Tag }}-amd64"
      - "flipt/flipt:v{{ .Major }}-beta-amd64"
      - "ghcr.io/flipt-io/flipt:v{{ .Tag }}-amd64"
      - "ghcr.io/flipt-io/flipt:v{{ .Major }}-beta-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - dockerfile: ./build/Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "flipt/flipt:v{{ .Tag }}-arm64"
      - "flipt/flipt:v{{ .Major }}-beta-arm64"
      - "ghcr.io/flipt-io/flipt:v{{ .Tag }}-arm64"
      - "ghcr.io/flipt-io/flipt:v{{ .Major }}-beta-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "flipt/flipt:v{{ .Tag }}"
    image_templates:
      - "flipt/flipt:v{{ .Tag }}-amd64"
      - "flipt/flipt:v{{ .Tag }}-arm64"

  - name_template: "ghcr.io/flipt-io/flipt:v{{ .Tag }}"
    image_templates:
      - "ghcr.io/flipt-io/flipt:v{{ .Tag }}-amd64"
      - "ghcr.io/flipt-io/flipt:v{{ .Tag }}-arm64"

  - name_template: "flipt/flipt:v{{ .Major }}-beta"
    image_templates:
      - "flipt/flipt:v{{ .Major }}-beta-amd64"
      - "flipt/flipt:v{{ .Major }}-beta-arm64"

  - name_template: "ghcr.io/flipt-io/flipt:v{{ .Major }}-beta"
    image_templates:
      - "ghcr.io/flipt-io/flipt:v{{ .Major }}-beta-amd64"
      - "ghcr.io/flipt-io/flipt:v{{ .Major }}-beta-arm64"

announce:
  discord:
    enabled: false
  slack:
    enabled: true
    channel: "#releases"

# brews:
#   - name: flipt@2
#     homepage: https://flipt.io
#     description: A Git-first, CloudNative feature management solution
#     license: FCL-1.0-MIT
#     directory: Formula
#     skip_upload: auto
#     install: |
#       bin.install "flipt"
#       output = Utils.popen_read("SHELL=bash #{bin}/flipt completion bash")
#       (bash_completion/"flipt").write output
#       output = Utils.popen_read("SHELL=zsh #{bin}/flipt completion zsh")
#       (zsh_completion/"_flipt").write output

#     post_install: |
#       (var/"log/flipt").mkpath

#     service: |
#       run [opt_bin/"flipt", "server"]
#       environment_variables PATH: std_service_path_env
#       keep_alive true
#       error_log_path "#{var}/log/flipt/server-stderr.log"
#       log_path "#{var}/log/flipt/server-stdout.log"

#     repository:
#       owner: flipt-io
#       name: homebrew-brew
#       branch: main
