# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

monorepo:
  tag_prefix: v

builds:
  - builder: prebuilt
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    ignore:
      - goos: darwin
        goarch: amd64
    prebuilt:
      path: tmp/dist/flipt_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/flipt
    binary: flipt

sboms:
  - artifacts: archive

archives:
  - id: main
    name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - CHANGELOG.md
      - ./config/default.yml

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto # enable rc releases (e.g. v1.0.0-rc.1)
  target_commitish: "{{ .Commit }}"
  footer: |
    ## Docker Images

    ```bash
      docker pull docker.io/flipt/flipt:v{{ .Tag }}
    ```

    ```bash
      docker pull ghcr.io/flipt-io/flipt:v{{ .Tag }}
    ```

    ## Thank you!

    We hope you :heart: this release! Feel free to open issues/discussions or reach out to us on Discord if you have any questions or feedback.

    - [Discord](https://flipt.io/discord)
    - [Github Discussions](https://github.com/flipt-io/flipt/discussions)
    - [Github Issues](https://github.com/flipt-io/flipt/issues)
    - [Newsletter](https://www.flipt.io/#newsletter)

snapshot:
  name_template: "{{ .ShortCommit }}-snapshot"

nightly:
  # Default is `{{ incpatch .Version }}-{{ .ShortCommit }}-nightly`.
  name_template: "{{ incpatch .Version }}-nightly"

changelog:
  skip: true

dockers:
  - dockerfile: ./build/Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "{{ if .IsNightly }}flipt/flipt:v{{ incpatch .Version }}-nightly-amd64{{ else }}flipt/flipt:v{{ .Tag }}-amd64{{ end }}"
      - "{{ if .IsNightly }}ghcr.io/flipt-io/flipt:v{{ incpatch .Version }}-nightly-amd64{{ else }}ghcr.io/flipt-io/flipt:v{{ .Tag }}-amd64{{ end }}"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - config/default.yml

  - dockerfile: ./build/Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "{{ if .IsNightly }}flipt/flipt:v{{ incpatch .Version }}-nightly-arm64{{ else }}flipt/flipt:v{{ .Tag }}-arm64{{ end }}"
      - "{{ if .IsNightly }}ghcr.io/flipt-io/flipt:v{{ incpatch .Version }}-nightly-arm64{{ else }}ghcr.io/flipt-io/flipt:v{{ .Tag }}-arm64{{ end }}"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - config/default.yml

docker_manifests:
  - name_template: "{{ if .IsNightly }}flipt/flipt:v{{ incpatch .Version }}-nightly{{ else }}flipt/flipt:v{{ .Tag }}{{ end }}"
    image_templates:
      - "{{ if .IsNightly }}flipt/flipt:v{{ incpatch .Version }}-nightly-amd64{{ else }}flipt/flipt:v{{ .Tag }}-amd64{{ end }}"
      - "{{ if .IsNightly }}flipt/flipt:v{{ incpatch .Version }}-nightly-arm64{{ else }}flipt/flipt:v{{ .Tag }}-arm64{{ end }}"

  - name_template: "{{ if .IsNightly }}markphelps/flipt:v{{ incpatch .Version }}-nightly{{ else }}markphelps/flipt:v{{ .Tag }}{{ end }}" # TODO: deprecate
    image_templates:
      - "{{ if .IsNightly }}flipt/flipt:v{{ incpatch .Version }}-nightly-amd64{{ else }}flipt/flipt:v{{ .Tag }}-amd64{{ end }}"
      - "{{ if .IsNightly }}flipt/flipt:v{{ incpatch .Version }}-nightly-arm64{{ else }}flipt/flipt:v{{ .Tag }}-arm64{{ end }}"

  - name_template: "{{ if .IsNightly }}ghcr.io/flipt-io/flipt:v{{ incpatch .Version }}-nightly{{ else }}ghcr.io/flipt-io/flipt:v{{ .Tag }}{{ end }}"
    image_templates:
      - "{{ if .IsNightly }}ghcr.io/flipt-io/flipt:v{{ incpatch .Version }}-nightly-amd64{{ else }}ghcr.io/flipt-io/flipt:v{{ .Tag }}-amd64{{ end }}"
      - "{{ if .IsNightly }}ghcr.io/flipt-io/flipt:v{{ incpatch .Version }}-nightly-arm64{{ else }}ghcr.io/flipt-io/flipt:v{{ .Tag }}-arm64{{ end }}"

announce:
  discord:
    enabled: true
  slack:
    enabled: true
    channel: '#releases'

brews:
  - name: flipt
    homepage: https://flipt.io
    description: An open source, self-hosted feature flag solution
    license: GPL-3.0-only
    folder: Formula
    skip_upload: auto

    post_install: |
      (var/"log/flipt").mkpath

    service: |
      run [opt_bin/"flipt"]
      environment_variables PATH: std_service_path_env
      keep_alive true
      error_log_path "#{var}/log/flipt/server-stderr.log"
      log_path "#{var}/log/flipt/server-stdout.log"

    repository:
      owner: flipt-io
      name: homebrew-brew
      branch: main
