builds:
  - main: ./cmd/flipt/.
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-musl-gcc
      - CXX=x86_64-linux-musl-g++
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
      - -linkmode external -extldflags -static
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: main
    replacements:
      amd64: x86_64
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - ./config/migrations/
      - ./config/default.yml

checksum:
  name_template: 'checksums.txt'

changelog:
  skip: true

dockers:
  - dockerfile: ./build/Dockerfile
    use_buildx: true
    image_templates:
      - "markphelps/flipt:latest"
      - "markphelps/flipt:{{ .Tag }}"
      - "ghcr.io/markphelps/flipt:latest"
      - "ghcr.io/markphelps/flipt:{{ .Tag }}"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - config/migrations/
      - config/default.yml