# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2

project_name: flipt

git:
  tag_sort: semver

monorepo:
  tag_prefix: v

builds:
  - builder: prebuilt
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    prebuilt:
      path: tmp/dist/flipt_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}{{ with .Arm64 }}_{{ . }}{{ end }}/flipt
    binary: flipt

sboms:
  - artifacts: archive

archives:
  - id: main
    name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto # enable rc releases (e.g. v1.0.0-rc.1)
  target_commitish: "{{ .Commit }}"

nightly:
  # Static v2-nightly version for all nightly builds from v2 branch
  version_template: "v2-nightly"

changelog:
  disable: true

dockers:
  - dockerfile: ./build/Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "flipt/flipt:{{ .Version }}-amd64"
      - "ghcr.io/flipt-io/flipt:{{ .Version }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - dockerfile: ./build/Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "flipt/flipt:{{ .Version }}-arm64"
      - "ghcr.io/flipt-io/flipt:{{ .Version }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "flipt/flipt:{{ .Version }}"
    image_templates:
      - "flipt/flipt:{{ .Version }}-amd64"
      - "flipt/flipt:{{ .Version }}-arm64"

  - name_template: "ghcr.io/flipt-io/flipt:{{ .Version }}"
    image_templates:
      - "ghcr.io/flipt-io/flipt:{{ .Version }}-amd64"
      - "ghcr.io/flipt-io/flipt:{{ .Version }}-arm64"
