env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/flipt/.
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: main
    replacements:
      amd64: x86_64
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - ./config/migrations/*
      - ./config/default.yml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

changelog:
  skip: true

dockers:
  - dockerfile: build/release/Dockerfile
    binaries:
      - flipt
    image_templates:
      - "markphelps/flipt:latest"
      - "markphelps/flipt:{{ .Tag }}"
    extra_files:
      - config
