# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2

project_name: flipt

git:
  tag_sort: semver

monorepo:
  tag_prefix: v

changelog:
  disable: true

builds:
  - main: ./cmd/flipt/.
    ldflags:
      - -s -w
      - -X main.version={{ .PrefixedTag }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}
      - -X main.analyticsKey={{ .Env.ANALYTICS_WRITE_KEY }}
      - -X main.analyticsEndpoint={{ .Env.ANALYTICS_WRITE_ENDPOINT }}
      - -X main.keygenVerifyKey={{ .Env.KEYGEN_VERIFY_KEY }}
      - -X main.keygenAccountID={{ .Env.KEYGEN_ACCOUNT_ID }}
      - -X main.keygenProductID={{ .Env.KEYGEN_PRODUCT_ID }}
      - -linkmode external -extldflags "-static"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=assets,netgo
      - -trimpath
    overrides:
      - goos: linux
        goarch: amd64
        goamd64: v1
        env:
          - CGO_ENABLED=1
          - CC=x86_64-linux-gnu-gcc

      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc

archives:
  - format: binary
