# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2

includes:
  - from_file:
      path: .goreleaser.yml

changelog:
  disable: true

docker_manifests:
  - name_template: "flipt/flipt:v2-nightly"
    image_templates:
      - "flipt/flipt:v2-nightly-amd64"
      - "flipt/flipt:v2-nightly-arm64"

  - name_template: "ghcr.io/flipt-io/flipt:v2-nightly"
    image_templates:
      - "ghcr.io/flipt-io/flipt:v2-nightly-amd64"
      - "ghcr.io/flipt-io/flipt:v2-nightly-arm64"
