builds:
  - main: ./cmd/flipt/.
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: main
    replacements:
      amd64: x86_64
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - ./config/migrations/*/**
      - ./config/default.yml

checksum:
  name_template: 'checksums.txt'

changelog:
  skip: true

dockers:
  - dockerfile: ./build/Dockerfile
    binaries:
      - flipt
    image_templates:
      - "markphelps/flipt:latest"
      - "markphelps/flipt:{{ .Tag }}"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - config
