snapshot:
  name_template: "{{ .ShortCommit }}-snapshot"

builds:
  - main: ./cmd/flipt/.
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .Date }} -X main.analyticsKey={{ .Env.ANALYTICS_KEY }}
      - -linkmode external -extldflags -static
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=assets,netgo
      - -trimpath

sboms:
  - artifacts: archive

archives:
  - id: main
    replacements:
      amd64: x86_64
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - ./config/migrations/
      - ./config/default.yml

checksum:
  name_template: "checksums.txt"

changelog:
  use: github-native

dockers:
  - dockerfile: ./build/Dockerfile
    use: buildx
    image_templates:
      - "flipt/flipt:latest"
      - "flipt/flipt:{{ .Tag }}"
      - "markphelps/flipt:latest" # TODO: deprecate
      - "markphelps/flipt:{{ .Tag }}" # TODO: deprecate
      - "ghcr.io/flipt-io/flipt:latest"
      - "ghcr.io/flipt-io/flipt:{{ .Tag }}"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - config/migrations/
      - config/default.yml

announce:
  discord:
    enabled: true
