sources:
  go: true
  yarn: true

apps:
  - source_path: ./cmd/flipt
    cache_path: ./.licenses
  - source_path: ./ui
    cache_path: ./.licenses/ui

allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - mpl-2.0
  - none
  - unlicense

ignored:
  go:
    - github.com/markphelps/flipt/**/*
