with-expecter: true
inpackage: True
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{ lower .InterfaceName }}.go"
packages:
  go.flipt.io/flipt/internal/server/environments:
    interfaces:
      Environment:
  go.flipt.io/flipt/internal/server/evaluation:
    interfaces:
      EnvironmentStore:
  go.flipt.io/flipt/internal/storage:
    interfaces:
      ReadOnlyStore:
