# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [commit-msg]
repos:
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
