ignore:
  - "_tools"
  - "build"
  - "examples"
  - "hack"
  - "internal/cmd/protoc-*"
  - "rpc/flipt/auth"
  - "rpc/flipt/flipt_grpc.pb.*"
  - "rpc/flipt/flipt.pb.*"
  - "rpc/flipt/meta"
  - "ui"
  - "**/mock_*.go"
