FROM golang:1.26-alpine

WORKDIR /server

RUN apk add --update --no-cache git bash gcc build-base binutils-gold \
  openssl \
  ca-certificates \
  postgresql-client \
  curl

RUN curl https://mise.run | sh
ENV PATH="/root/.local/bin:$PATH"

COPY go.mod .
COPY go.sum .
COPY .mise.toml .
COPY ./errors ./errors
COPY ./rpc/flipt ./rpc/flipt
COPY ./sdk ./sdk
COPY ./core ./core

RUN go mod download -x

RUN mkdir -p /etc/flipt && \
  mkdir -p /var/opt/flipt

EXPOSE 8080
EXPOSE 9000
EXPOSE 5173
