services:
  - type: pserv
    name: flipt
    runtime: image
    plan: standard
    image:
      url: ghcr.io/flipt-io/flipt:latest
    disk:
      name: data
      mountPath: /var/opt/flipt
      sizeGB: 5