# https://taskfile.dev/
version: 3

vars:
  PROJECT: flipt
  SOURCE_FILES: ./...
  UI: ui
  COVERAGE_FILE: coverage.txt

tasks:
  default:
    desc: Build the binary
    deps: [prep]
    cmds:
      - go build -trimpath -tags assets -ldflags "-X main.commit={{.GIT_COMMIT}} -X main.date={{.BUILD_DATE}}" -o {{.OUTPUT}}/{{.PROJECT}} ./cmd/{{.PROJECT}}/.
    vars:
      OUTPUT: '{{default "./bin" .OUTPUT}}'
      GIT_COMMIT:
        sh: set -e && git rev-parse --verify HEAD || ""
      BUILD_DATE:
        sh: date -u +%Y-%m-%dT%H:%M:%SZ

  prep:
    desc: Prepare for release
    cmds:
      - task: clean
      - task: proto
      - task: assets

  pkg:
    desc: Package the binary
    cmds:
      - task: default
        vars: { OUTPUT: "./pkg" }
      - mkdir -p ./pkg/config/migrations
      - cp -R ./config/migrations/ ./pkg/config/migrations/
      - cp ./config/*.yml ./pkg/config/
    vars:
      GIT_COMMIT:
        sh: set -e && git rev-parse --verify HEAD || ""

  assets:
    desc: Build the UI
    deps: [assets:deps]
    dir: "{{.UI}}"
    cmds:
      - npm run build
    sources:
      - ./{{.UI}}/static/*
      - ./{{.UI}}/src/**/*
      - ./{{.UI}}/src/**/**/*
      - ./{{.UI}}/index.html
      - ./{{.UI}}/package.json
    method: checksum

  assets:deps:
    desc: Install UI dependencies
    dir: "{{.UI}}"
    cmds:
      - npm ci
    sources:
      - ./{{.UI}}/package-lock.json
    method: checksum

  assets:dev:
    desc: Run the UI dev server
    dir: "{{.UI}}"
    cmds:
      - npm run dev

  bootstrap:
    desc: Install necessary development tools
    cmds:
      - ./script/bootstrap
    sources:
      - ./_tools/go.mod
    generates:
      - ./_tools/go.sum
    method: checksum

  build:
    desc: Run Go build
    cmds:
      - go build -trimpath -tags assets -ldflags "-X main.commit={{.GIT_COMMIT}}" -o ./bin/{{.PROJECT}} ./cmd/{{.PROJECT}}/.
    vars:
      GIT_COMMIT:
        sh: set -e && git rev-parse --verify HEAD || ""

  build:clients:
    desc: Generate Ruby and Go proto clients
    deps: [proto]
    cmds:
      - buf generate --template=buf.public.gen.yaml

  proto:
    desc: Generate protobuf files from .protos
    deps: [bootstrap]
    cmds:
      - buf generate

  dev:
    desc: Run the server and UI in development mode
    cmds:
      - script/server

  server:
    desc: Start the server
    cmds:
      - go run ./cmd/flipt/. --config ./config/local.yml --force-migrate

  clean:
    desc: Remove built assets
    cmds:
      - go mod tidy
      - go clean -i {{.SOURCE_FILES}}
      - rm -rf dist/*
      - rm -rf pkg/*
      - rm -rf bin/*

  cover:
    desc: Run test coverage
    deps: [test]
    cmds:
      - go tool cover -html={{.COVERAGE_FILE}}

  fmt:
    desc: Run goimports
    cmds:
      - goimports -w $(go list -f {{`{{.Dir}}`}} ./... | grep -v /rpc/)

  lint:
    desc: Run the linters
    cmds:
      - golangci-lint run 2>&1
      - buf lint

  test:
    desc: Run all the tests
    cmds:
      - go test {{.TEST_OPTS}} -covermode=atomic -count=1 -coverprofile={{.COVERAGE_FILE}} {{.SOURCE_FILES}} -run={{.TEST_PATTERN}} -timeout=30s
    vars:
      TEST_PATTERN: '{{.TEST_PATTERN | default "."}}'
      TEST_OPTS: '{{.TEST_OPTS | default "-race"}}'
    env:
      FLIPT_TEST_DATABASE_PROTOCOL: '{{.FLIPT_TEST_DATABASE_PROTOCOL | default "sqlite"}}'

  test:mysql:
    desc: Run all the tests with MySQL db backend
    cmds:
      - task: test
        vars: { FLIPT_TEST_DATABASE_PROTOCOL: "mysql" }

  test:postgres:
    desc: Run all the tests with Postgres db backend
    cmds:
      - task: test
        vars: { FLIPT_TEST_DATABASE_PROTOCOL: "postgres" }
