version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
  primary:
    build: .
    privileged: true
    ports:
      - "8081:8080"
    environment:
      IS_PRIMARY: "true"
  replica:
    build: .
    ports:
      - "8082:8080"
    restart: on-failure
    privileged: true
    environment:
      IS_PRIMARY: "false"
