version: "3"

services:
  redis:
    image: redis:latest
    networks:
      - flipt_network

  flipt:
    build: .
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - flipt_network
    environment:
      - FLIPT_CACHE_ENABLED=true
      - FLIPT_CACHE_TTL=60s
      - FLIPT_CACHE_BACKEND=redis
      - FLIPT_CACHE_REDIS_HOST=redis
      - FLIPT_CACHE_REDIS_PORT=6379
      - FLIPT_LOG_LEVEL=debug
    command: ["./tmp/wait-for-it.sh", "redis:6379", "--", "./flipt", "--force-migrate"]

networks:
  flipt_network:
