version: "3"

services:
  redis:
    image: redis:latest
    networks:
      - flipt_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]

  flipt:
    image: flipt/flipt:latest
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - flipt_network
    environment:
      - FLIPT_CACHE_ENABLED=true
      - FLIPT_CACHE_TTL=60s
      - FLIPT_CACHE_BACKEND=redis
      - FLIPT_CACHE_REDIS_HOST=redis
      - FLIPT_CACHE_REDIS_PORT=6379
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_META_TELEMETRY_ENABLED=false
    command: ["/flipt", "--force-migrate"]

networks:
  flipt_network:
