// Code generated by protoc-gen-go-flipt-sdk. DO NOT EDIT.

package sdk

import (
	context "context"
	analytics "go.flipt.io/flipt/rpc/flipt/analytics"
)

type Analytics struct {
	transport              analytics.AnalyticsServiceClient
	authenticationProvider ClientAuthenticationProvider
}

func (x *Analytics) GetFlagEvaluationsCount(ctx context.Context, v *analytics.GetFlagEvaluationsCountRequest) (*analytics.GetFlagEvaluationsCountResponse, error) {
	ctx, err := authenticate(ctx, x.authenticationProvider)
	if err != nil {
		return nil, err
	}
	return x.transport.GetFlagEvaluationsCount(ctx, v)
}
