// Code generated by protoc-gen-go-flipt-sdk. DO NOT EDIT.

package sdk

import (
	audit "go.flipt.io/flipt/rpc/flipt/audit"
)

type Audit struct {
	transport              audit.AuditEventServiceClient
	authenticationProvider ClientAuthenticationProvider
}
