// Code generated by protoc-gen-go-flipt-sdk. DO NOT EDIT.

package sdk

import (
	flipt "go.flipt.io/flipt/rpc/flipt"
	auth "go.flipt.io/flipt/rpc/flipt/auth"
	meta "go.flipt.io/flipt/rpc/flipt/meta"
	grpc "google.golang.org/grpc"
)

type GRPCTransport struct {
	cc grpc.ClientConnInterface
}

func NewGRPCTransport(cc grpc.ClientConnInterface) GRPCTransport {
	return GRPCTransport{cc: cc}
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func (t authClient) PublicAuthenticationServiceClient() auth.PublicAuthenticationServiceClient {
	return auth.NewPublicAuthenticationServiceClient(t.cc)
}

func (t authClient) AuthenticationServiceClient() auth.AuthenticationServiceClient {
	return auth.NewAuthenticationServiceClient(t.cc)
}

func (t authClient) AuthenticationMethodTokenServiceClient() auth.AuthenticationMethodTokenServiceClient {
	return auth.NewAuthenticationMethodTokenServiceClient(t.cc)
}

func (t authClient) AuthenticationMethodOIDCServiceClient() auth.AuthenticationMethodOIDCServiceClient {
	return auth.NewAuthenticationMethodOIDCServiceClient(t.cc)
}

func (t authClient) AuthenticationMethodKubernetesServiceClient() auth.AuthenticationMethodKubernetesServiceClient {
	return auth.NewAuthenticationMethodKubernetesServiceClient(t.cc)
}

func (t GRPCTransport) AuthClient() AuthClient {
	return authClient{cc: t.cc}
}

func (t GRPCTransport) FliptClient() flipt.FliptClient {
	return flipt.NewFliptClient(t.cc)
}

func (t GRPCTransport) MetaClient() meta.MetadataServiceClient {
	return meta.NewMetadataServiceClient(t.cc)
}
