version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.16
    ports:
      - "16686:16686"
    networks:
      - flipt_network
    environment:
      - "COLLECTOR_ZIPKIN_HTTP_PORT=9411"

  flipt:
    image: markphelps/flipt:latest
    depends_on:
      - jaeger
    ports:
      - "8080:8080"
    networks:
      - flipt_network
    environment:
      - "FLIPT_LOG_LEVEL=debug"
      - "FLIPT_TRACING_JAEGER_ENABLED=true"
      - "FLIPT_TRACING_JAEGER_HOST=jaeger"

networks:
  flipt_network:
