version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    networks:
      - flipt_network
    environment:
      - "COLLECTOR_ZIPKIN_HOST_PORT=:9411"
      - "COLLECTOR_OTLP_ENABLED=true"

  flipt:
    image: flipt/flipt:latest
    depends_on:
      - jaeger
    ports:
      - "8080:8080"
    networks:
      - flipt_network
    environment:
      - "FLIPT_LOG_LEVEL=debug"
      - "FLIPT_TRACING_JAEGER_ENABLED=true"
      - "FLIPT_TRACING_JAEGER_HOST=jaeger"

networks:
  flipt_network:
