issuer: http://dex:5556/dex

storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db

web:
  http: dex:5556

enablePasswordDB: true

staticClients:
- id: flipt
  redirectURIs:
  - 'http://localhost:8080/auth/v1/method/oidc/dex/callback'
  name: 'Flipt'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0

staticPasswords:
- email: "admin@example.com"
  # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
