// Code generated by protoc-gen-go-flipt-sdk. DO NOT EDIT.

package http

import (
	audit "go.flipt.io/flipt/rpc/flipt/audit"
	http "net/http"
)

type AuditEventServiceClient struct {
	client *http.Client
	addr   string
}

func (t Transport) AuditClient() audit.AuditEventServiceClient {
	return &AuditEventServiceClient{client: t.client, addr: t.addr}
}
