// Code generated by protoc-gen-go-flipt-sdk. DO NOT EDIT.

package http

import (
	data "go.flipt.io/flipt/rpc/flipt/data"
	http "net/http"
)

type DataClient struct {
	client *http.Client
	addr   string
}

func (t Transport) DataClient() data.DataClient {
	return &DataClient{client: t.client, addr: t.addr}
}
