// Code generated by protoc-gen-go-flipt-sdk. DO NOT EDIT.

package http

import (
	context "context"
	ofrep "go.flipt.io/flipt/rpc/flipt/ofrep"
	grpc "google.golang.org/grpc"
	protojson "google.golang.org/protobuf/encoding/protojson"
	io "io"
	http "net/http"
	url "net/url"
)

type OFREPServiceClient struct {
	client *http.Client
	addr   string
}

func (x *OFREPServiceClient) GetProviderConfiguration(ctx context.Context, v *ofrep.GetProviderConfigurationRequest, _ ...grpc.CallOption) (*ofrep.GetProviderConfigurationResponse, error) {
	var body io.Reader
	var values url.Values
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, x.addr+"/ofrep/*/ofrep/v1/configuration", body)
	if err != nil {
		return nil, err
	}
	req.URL.RawQuery = values.Encode()
	resp, err := x.client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	var output ofrep.GetProviderConfigurationResponse
	respData, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if err := checkResponse(resp, respData); err != nil {
		return nil, err
	}
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(respData, &output); err != nil {
		return nil, err
	}
	return &output, nil
}

func (t Transport) OfrepClient() ofrep.OFREPServiceClient {
	return &OFREPServiceClient{client: t.client, addr: t.addr}
}
