// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: analytics.proto

package analytics

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/visibility"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFlagEvaluationsCountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentKey string                 `protobuf:"bytes,1,opt,name=environment_key,json=environmentKey,proto3" json:"environment_key,omitempty"`
	NamespaceKey   string                 `protobuf:"bytes,2,opt,name=namespace_key,json=namespaceKey,proto3" json:"namespace_key,omitempty"`
	FlagKey        string                 `protobuf:"bytes,3,opt,name=flag_key,json=flagKey,proto3" json:"flag_key,omitempty"`
	From           string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To             string                 `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFlagEvaluationsCountRequest) Reset() {
	*x = GetFlagEvaluationsCountRequest{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlagEvaluationsCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagEvaluationsCountRequest) ProtoMessage() {}

func (x *GetFlagEvaluationsCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagEvaluationsCountRequest.ProtoReflect.Descriptor instead.
func (*GetFlagEvaluationsCountRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetFlagEvaluationsCountRequest) GetEnvironmentKey() string {
	if x != nil {
		return x.EnvironmentKey
	}
	return ""
}

func (x *GetFlagEvaluationsCountRequest) GetNamespaceKey() string {
	if x != nil {
		return x.NamespaceKey
	}
	return ""
}

func (x *GetFlagEvaluationsCountRequest) GetFlagKey() string {
	if x != nil {
		return x.FlagKey
	}
	return ""
}

func (x *GetFlagEvaluationsCountRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetFlagEvaluationsCountRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type GetFlagEvaluationsCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamps    []string               `protobuf:"bytes,1,rep,name=timestamps,proto3" json:"timestamps,omitempty"`
	Values        []float32              `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlagEvaluationsCountResponse) Reset() {
	*x = GetFlagEvaluationsCountResponse{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlagEvaluationsCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlagEvaluationsCountResponse) ProtoMessage() {}

func (x *GetFlagEvaluationsCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlagEvaluationsCountResponse.ProtoReflect.Descriptor instead.
func (*GetFlagEvaluationsCountResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetFlagEvaluationsCountResponse) GetTimestamps() []string {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

func (x *GetFlagEvaluationsCountResponse) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\tanalytics\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/api/visibility.proto\"\xad\x01\n" +
	"\x1eGetFlagEvaluationsCountRequest\x12'\n" +
	"\x0fenvironment_key\x18\x01 \x01(\tR\x0eenvironmentKey\x12#\n" +
	"\rnamespace_key\x18\x02 \x01(\tR\fnamespaceKey\x12\x19\n" +
	"\bflag_key\x18\x03 \x01(\tR\aflagKey\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\tR\x02to\"Y\n" +
	"\x1fGetFlagEvaluationsCountResponse\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x01 \x03(\tR\n" +
	"timestamps\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x02R\x06values2\xf0\x01\n" +
	"\x10AnalyticsService\x12\xdb\x01\n" +
	"\x17GetFlagEvaluationsCount\x12).analytics.GetFlagEvaluationsCountRequest\x1a*.analytics.GetFlagEvaluationsCountResponse\"i\x82\xd3\xe4\x93\x02c\x12a/internal/v2/analytics/environments/{environment_key}/namespaces/{namespace_key}/flags/{flag_key}B$Z\"go.flipt.io/flipt/rpc/v2/analyticsb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_analytics_proto_goTypes = []any{
	(*GetFlagEvaluationsCountRequest)(nil),  // 0: analytics.GetFlagEvaluationsCountRequest
	(*GetFlagEvaluationsCountResponse)(nil), // 1: analytics.GetFlagEvaluationsCountResponse
}
var file_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.AnalyticsService.GetFlagEvaluationsCount:input_type -> analytics.GetFlagEvaluationsCountRequest
	1, // 1: analytics.AnalyticsService.GetFlagEvaluationsCount:output_type -> analytics.GetFlagEvaluationsCountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
