name: Feature request
description: Suggest an idea for this project (v2)
labels: ["enhancement", "v2"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

        Please note that new features will only be added to the v2 version of Flipt.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
      placeholder: Describe the problem you are trying to solve here...
    validations:
      required: true

  - type: textarea
    id: ideal-solution
    attributes:
      label: Ideal Solution
      description: What would you like to happen?
      placeholder: Describe the solution you'd like...
    validations:
      required: true

  - type: checkbox
    id: v2-only
    attributes:
      label: I understand that this feature will only be added to the v2 version of Flipt
      required: true

  - type: checkboxes
    id: search
    attributes:
      label: Search
      options:
        - label: I searched for other open and closed issues before opening this
          required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.