name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
      placeholder: Describe the problem you are trying to solve here...
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Which major version?
      description: Please select the major version of Flipt that you are experiencing the feature request with.
      options:
        - v1
        - v2

  - type: textarea
    id: ideal-solution
    attributes:
      label: Ideal Solution
      description: What would you like to happen?
      placeholder: Describe the solution you'd like...

  - type: checkboxes
    id: search
    attributes:
      label: Search
      options:
        - label: I searched for other open and closed issues before opening this
          required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here.
      placeholder: |
        Examples:

        - OS
        - Config file used
        - Screenshots
