version: "3"

services:
  flipt:
    image: flipt/flipt:latest
    environment:
      - FLIPT_LOG_LEVEL=warn
      - FLIPT_STORAGE_TYPE=local
      - FLIPT_STORAGE_LOCAL_PATH=/opt
      - FLIPT_META_TELEMETRY_ENABLED=false
    networks:
      - flipt_network
    volumes:
      - ./features.yml:/opt/features.yml:ro
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1

  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    networks:
      - flipt_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      flipt:
        condition: service_healthy

networks:
  flipt_network:
