// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ofrep/ofrep.proto

package ofrep

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/visibility"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluateReason int32

const (
	EvaluateReason_UNKNOWN         EvaluateReason = 0
	EvaluateReason_DISABLED        EvaluateReason = 1
	EvaluateReason_TARGETING_MATCH EvaluateReason = 2
	EvaluateReason_DEFAULT         EvaluateReason = 3
)

// Enum value maps for EvaluateReason.
var (
	EvaluateReason_name = map[int32]string{
		0: "UNKNOWN",
		1: "DISABLED",
		2: "TARGETING_MATCH",
		3: "DEFAULT",
	}
	EvaluateReason_value = map[string]int32{
		"UNKNOWN":         0,
		"DISABLED":        1,
		"TARGETING_MATCH": 2,
		"DEFAULT":         3,
	}
)

func (x EvaluateReason) Enum() *EvaluateReason {
	p := new(EvaluateReason)
	*p = x
	return p
}

func (x EvaluateReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvaluateReason) Descriptor() protoreflect.EnumDescriptor {
	return file_ofrep_ofrep_proto_enumTypes[0].Descriptor()
}

func (EvaluateReason) Type() protoreflect.EnumType {
	return &file_ofrep_ofrep_proto_enumTypes[0]
}

func (x EvaluateReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvaluateReason.Descriptor instead.
func (EvaluateReason) EnumDescriptor() ([]byte, []int) {
	return file_ofrep_ofrep_proto_rawDescGZIP(), []int{0}
}

type GetProviderConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderConfigurationRequest) Reset() {
	*x = GetProviderConfigurationRequest{}
	mi := &file_ofrep_ofrep_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderConfigurationRequest) ProtoMessage() {}

func (x *GetProviderConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ofrep_ofrep_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetProviderConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_ofrep_ofrep_proto_rawDescGZIP(), []int{0}
}

type GetProviderConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Capabilities  *Capabilities          `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderConfigurationResponse) Reset() {
	*x = GetProviderConfigurationResponse{}
	mi := &file_ofrep_ofrep_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderConfigurationResponse) ProtoMessage() {}

func (x *GetProviderConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ofrep_ofrep_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetProviderConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_ofrep_ofrep_proto_rawDescGZIP(), []int{1}
}

func (x *GetProviderConfigurationResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProviderConfigurationResponse) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Capabilities struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CacheInvalidation *CacheInvalidation     `protobuf:"bytes,1,opt,name=cache_invalidation,json=cacheInvalidation,proto3" json:"cache_invalidation,omitempty"`
	FlagEvaluation    *FlagEvaluation        `protobuf:"bytes,2,opt,name=flag_evaluation,json=flagEvaluation,proto3" json:"flag_evaluation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_ofrep_ofrep_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_ofrep_ofrep_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_ofrep_ofrep_proto_rawDescGZIP(), []int{2}
}

func (x *Capabilities) GetCacheInvalidation() *CacheInvalidation {
	if x != nil {
		return x.CacheInvalidation
	}
	return nil
}

func (x *Capabilities) GetFlagEvaluation() *FlagEvaluation {
	if x != nil {
		return x.FlagEvaluation
	}
	return nil
}

type CacheInvalidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polling       *Polling               `protobuf:"bytes,1,opt,name=polling,proto3" json:"polling,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheInvalidation) Reset() {
	*x = CacheInvalidation{}
	mi := &file_ofrep_ofrep_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheInvalidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheInvalidation) ProtoMessage() {}

func (x *CacheInvalidation) ProtoReflect() protoreflect.Message {
	mi := &file_ofrep_ofrep_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheInvalidation.ProtoReflect.Descriptor instead.
func (*CacheInvalidation) Descriptor() ([]byte, []int) {
	return file_ofrep_ofrep_proto_rawDescGZIP(), []int{3}
}

func (x *CacheInvalidation) GetPolling() *Polling {
	if x != nil {
		return x.Polling
	}
	return nil
}

type Polling struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Enabled              bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MinPollingIntervalMs uint32                 `protobuf:"varint,2,opt,name=min_polling_interval_ms,json=minPollingIntervalMs,proto3" json:"min_polling_interval_ms,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Polling) Reset() {
	*x = Polling{}
	mi := &file_ofrep_ofrep_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Polling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Polling) ProtoMessage() {}

func (x *Polling) ProtoReflect() protoreflect.Message {
	mi := &file_ofrep_ofrep_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Polling.ProtoReflect.Descriptor instead.
func (*Polling) Descriptor() ([]byte, []int) {
	return file_ofrep_ofrep_proto_rawDescGZIP(), []int{4}
}

func (x *Polling) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Polling) GetMinPollingIntervalMs() uint32 {
	if x != nil {
		return x.MinPollingIntervalMs
	}
	return 0
}

type FlagEvaluation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SupportedTypes []string               `protobuf:"bytes,1,rep,name=supported_types,json=supportedTypes,proto3" json:"supported_types,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FlagEvaluation) Reset() {
	*x = FlagEvaluation{}
	mi := &file_ofrep_ofrep_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagEvaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagEvaluation) ProtoMessage() {}

func (x *FlagEvaluation) ProtoReflect() protoreflect.Message {
	mi := &file_ofrep_ofrep_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagEvaluation.ProtoReflect.Descriptor instead.
func (*FlagEvaluation) Descriptor() ([]byte, []int) {
	return file_ofrep_ofrep_proto_rawDescGZIP(), []int{5}
}

func (x *FlagEvaluation) GetSupportedTypes() []string {
	if x != nil {
		return x.SupportedTypes
	}
	return nil
}

type EvaluateFlagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Context       map[string]string      `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateFlagRequest) Reset() {
	*x = EvaluateFlagRequest{}
	mi := &file_ofrep_ofrep_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateFlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateFlagRequest) ProtoMessage() {}

func (x *EvaluateFlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ofrep_ofrep_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateFlagRequest.ProtoReflect.Descriptor instead.
func (*EvaluateFlagRequest) Descriptor() ([]byte, []int) {
	return file_ofrep_ofrep_proto_rawDescGZIP(), []int{6}
}

func (x *EvaluateFlagRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EvaluateFlagRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type EvaluationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Reason        EvaluateReason         `protobuf:"varint,2,opt,name=reason,proto3,enum=flipt.ofrep.EvaluateReason" json:"reason,omitempty"`
	Variant       string                 `protobuf:"bytes,3,opt,name=variant,proto3" json:"variant,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluationResponse) Reset() {
	*x = EvaluationResponse{}
	mi := &file_ofrep_ofrep_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationResponse) ProtoMessage() {}

func (x *EvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ofrep_ofrep_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationResponse.ProtoReflect.Descriptor instead.
func (*EvaluationResponse) Descriptor() ([]byte, []int) {
	return file_ofrep_ofrep_proto_rawDescGZIP(), []int{7}
}

func (x *EvaluationResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EvaluationResponse) GetReason() EvaluateReason {
	if x != nil {
		return x.Reason
	}
	return EvaluateReason_UNKNOWN
}

func (x *EvaluationResponse) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *EvaluationResponse) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EvaluationResponse) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type EvaluateBulkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       map[string]string      `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateBulkRequest) Reset() {
	*x = EvaluateBulkRequest{}
	mi := &file_ofrep_ofrep_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateBulkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateBulkRequest) ProtoMessage() {}

func (x *EvaluateBulkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ofrep_ofrep_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateBulkRequest.ProtoReflect.Descriptor instead.
func (*EvaluateBulkRequest) Descriptor() ([]byte, []int) {
	return file_ofrep_ofrep_proto_rawDescGZIP(), []int{8}
}

func (x *EvaluateBulkRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type BulkEvaluationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         []*EvaluationResponse  `protobuf:"bytes,1,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkEvaluationResponse) Reset() {
	*x = BulkEvaluationResponse{}
	mi := &file_ofrep_ofrep_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkEvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkEvaluationResponse) ProtoMessage() {}

func (x *BulkEvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ofrep_ofrep_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkEvaluationResponse.ProtoReflect.Descriptor instead.
func (*BulkEvaluationResponse) Descriptor() ([]byte, []int) {
	return file_ofrep_ofrep_proto_rawDescGZIP(), []int{9}
}

func (x *BulkEvaluationResponse) GetFlags() []*EvaluationResponse {
	if x != nil {
		return x.Flags
	}
	return nil
}

var File_ofrep_ofrep_proto protoreflect.FileDescriptor

const file_ofrep_ofrep_proto_rawDesc = "" +
	"\n" +
	"\x11ofrep/ofrep.proto\x12\vflipt.ofrep\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/api/visibility.proto\x1a\x1cgoogle/protobuf/struct.proto\"!\n" +
	"\x1fGetProviderConfigurationRequest\"u\n" +
	" GetProviderConfigurationResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\fcapabilities\x18\x02 \x01(\v2\x19.flipt.ofrep.CapabilitiesR\fcapabilities\"\xa3\x01\n" +
	"\fCapabilities\x12M\n" +
	"\x12cache_invalidation\x18\x01 \x01(\v2\x1e.flipt.ofrep.CacheInvalidationR\x11cacheInvalidation\x12D\n" +
	"\x0fflag_evaluation\x18\x02 \x01(\v2\x1b.flipt.ofrep.FlagEvaluationR\x0eflagEvaluation\"C\n" +
	"\x11CacheInvalidation\x12.\n" +
	"\apolling\x18\x01 \x01(\v2\x14.flipt.ofrep.PollingR\apolling\"Z\n" +
	"\aPolling\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x125\n" +
	"\x17min_polling_interval_ms\x18\x02 \x01(\rR\x14minPollingIntervalMs\"9\n" +
	"\x0eFlagEvaluation\x12'\n" +
	"\x0fsupported_types\x18\x01 \x03(\tR\x0esupportedTypes\"\xac\x01\n" +
	"\x13EvaluateFlagRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12G\n" +
	"\acontext\x18\x02 \x03(\v2-.flipt.ofrep.EvaluateFlagRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x01\n" +
	"\x12EvaluationResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1b.flipt.ofrep.EvaluateReasonR\x06reason\x12\x18\n" +
	"\avariant\x18\x03 \x01(\tR\avariant\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12,\n" +
	"\x05value\x18\x05 \x01(\v2\x16.google.protobuf.ValueR\x05value\"\x9a\x01\n" +
	"\x13EvaluateBulkRequest\x12G\n" +
	"\acontext\x18\x02 \x03(\v2-.flipt.ofrep.EvaluateBulkRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x16BulkEvaluationResponse\x12:\n" +
	"\x05flags\x18\x01 \x03(\v2\x1f.flipt.ofrep.EvaluationResponseB\x03\xe0A\x02R\x05flags*M\n" +
	"\x0eEvaluateReason\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bDISABLED\x10\x01\x12\x13\n" +
	"\x0fTARGETING_MATCH\x10\x02\x12\v\n" +
	"\aDEFAULT\x10\x032\x85\x04\n" +
	"\fOFREPService\x12\xb0\x01\n" +
	"\x18GetProviderConfiguration\x12,.flipt.ofrep.GetProviderConfigurationRequest\x1a-.flipt.ofrep.GetProviderConfigurationResponse\"7\xbaG\x15*\x13ofrep.configuration\x82\xd3\xe4\x93\x02\x19\x12\x17/ofrep/v1/configuration\x12\x93\x01\n" +
	"\fEvaluateFlag\x12 .flipt.ofrep.EvaluateFlagRequest\x1a\x1f.flipt.ofrep.EvaluationResponse\"@\xbaG\x14*\x12ofrep.evaluateFlag\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/ofrep/v1/evaluate/flags/{key}\x12\x91\x01\n" +
	"\fEvaluateBulk\x12 .flipt.ofrep.EvaluateBulkRequest\x1a#.flipt.ofrep.BulkEvaluationResponse\":\xbaG\x14*\x12ofrep.evaluateBulk\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/ofrep/v1/evaluate/flags\x1a\x18\xfa\xd2\xe4\x93\x02\x12\x12\x10flipt:sdk:ignoreB#Z!go.flipt.io/flipt/rpc/flipt/ofrepb\x06proto3"

var (
	file_ofrep_ofrep_proto_rawDescOnce sync.Once
	file_ofrep_ofrep_proto_rawDescData []byte
)

func file_ofrep_ofrep_proto_rawDescGZIP() []byte {
	file_ofrep_ofrep_proto_rawDescOnce.Do(func() {
		file_ofrep_ofrep_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ofrep_ofrep_proto_rawDesc), len(file_ofrep_ofrep_proto_rawDesc)))
	})
	return file_ofrep_ofrep_proto_rawDescData
}

var file_ofrep_ofrep_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ofrep_ofrep_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ofrep_ofrep_proto_goTypes = []any{
	(EvaluateReason)(0),                      // 0: flipt.ofrep.EvaluateReason
	(*GetProviderConfigurationRequest)(nil),  // 1: flipt.ofrep.GetProviderConfigurationRequest
	(*GetProviderConfigurationResponse)(nil), // 2: flipt.ofrep.GetProviderConfigurationResponse
	(*Capabilities)(nil),                     // 3: flipt.ofrep.Capabilities
	(*CacheInvalidation)(nil),                // 4: flipt.ofrep.CacheInvalidation
	(*Polling)(nil),                          // 5: flipt.ofrep.Polling
	(*FlagEvaluation)(nil),                   // 6: flipt.ofrep.FlagEvaluation
	(*EvaluateFlagRequest)(nil),              // 7: flipt.ofrep.EvaluateFlagRequest
	(*EvaluationResponse)(nil),               // 8: flipt.ofrep.EvaluationResponse
	(*EvaluateBulkRequest)(nil),              // 9: flipt.ofrep.EvaluateBulkRequest
	(*BulkEvaluationResponse)(nil),           // 10: flipt.ofrep.BulkEvaluationResponse
	nil,                                      // 11: flipt.ofrep.EvaluateFlagRequest.ContextEntry
	nil,                                      // 12: flipt.ofrep.EvaluateBulkRequest.ContextEntry
	(*structpb.Struct)(nil),                  // 13: google.protobuf.Struct
	(*structpb.Value)(nil),                   // 14: google.protobuf.Value
}
var file_ofrep_ofrep_proto_depIdxs = []int32{
	3,  // 0: flipt.ofrep.GetProviderConfigurationResponse.capabilities:type_name -> flipt.ofrep.Capabilities
	4,  // 1: flipt.ofrep.Capabilities.cache_invalidation:type_name -> flipt.ofrep.CacheInvalidation
	6,  // 2: flipt.ofrep.Capabilities.flag_evaluation:type_name -> flipt.ofrep.FlagEvaluation
	5,  // 3: flipt.ofrep.CacheInvalidation.polling:type_name -> flipt.ofrep.Polling
	11, // 4: flipt.ofrep.EvaluateFlagRequest.context:type_name -> flipt.ofrep.EvaluateFlagRequest.ContextEntry
	0,  // 5: flipt.ofrep.EvaluationResponse.reason:type_name -> flipt.ofrep.EvaluateReason
	13, // 6: flipt.ofrep.EvaluationResponse.metadata:type_name -> google.protobuf.Struct
	14, // 7: flipt.ofrep.EvaluationResponse.value:type_name -> google.protobuf.Value
	12, // 8: flipt.ofrep.EvaluateBulkRequest.context:type_name -> flipt.ofrep.EvaluateBulkRequest.ContextEntry
	8,  // 9: flipt.ofrep.BulkEvaluationResponse.flags:type_name -> flipt.ofrep.EvaluationResponse
	1,  // 10: flipt.ofrep.OFREPService.GetProviderConfiguration:input_type -> flipt.ofrep.GetProviderConfigurationRequest
	7,  // 11: flipt.ofrep.OFREPService.EvaluateFlag:input_type -> flipt.ofrep.EvaluateFlagRequest
	9,  // 12: flipt.ofrep.OFREPService.EvaluateBulk:input_type -> flipt.ofrep.EvaluateBulkRequest
	2,  // 13: flipt.ofrep.OFREPService.GetProviderConfiguration:output_type -> flipt.ofrep.GetProviderConfigurationResponse
	8,  // 14: flipt.ofrep.OFREPService.EvaluateFlag:output_type -> flipt.ofrep.EvaluationResponse
	10, // 15: flipt.ofrep.OFREPService.EvaluateBulk:output_type -> flipt.ofrep.BulkEvaluationResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_ofrep_ofrep_proto_init() }
func file_ofrep_ofrep_proto_init() {
	if File_ofrep_ofrep_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ofrep_ofrep_proto_rawDesc), len(file_ofrep_ofrep_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ofrep_ofrep_proto_goTypes,
		DependencyIndexes: file_ofrep_ofrep_proto_depIdxs,
		EnumInfos:         file_ofrep_ofrep_proto_enumTypes,
		MessageInfos:      file_ofrep_ofrep_proto_msgTypes,
	}.Build()
	File_ofrep_ofrep_proto = out.File
	file_ofrep_ofrep_proto_goTypes = nil
	file_ofrep_ofrep_proto_depIdxs = nil
}
