# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision :shell, path: "setup.sh", privileged: false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 9000, host: 9000, host_ip: "127.0.0.1"

  # If this shared folder fails, you likely need to install the Vagrant
  # guest extensions, install this plugin to do so:
  #
  # vagrant plugin install vagrant-vbguest
  config.vm.synced_folder "../..", "/flipt"
end
