apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Release.Name }}"
  name: "{{ .Release.Name }}"
spec:
  clusterIP:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30509
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: "{{ .Release.Name }}"
  sessionAffinity: None
  type: "{{ .Values.service.type }}"
status:
  loadBalancer: {}
