apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flipt.fullname" . }}
  labels:
    {{- include "flipt.labels" . | nindent 4 }}
data:
  config.yml: |
    log:
      level: WARN

    server:
      protocol: http
      host: 0.0.0.0
      http_port: 8080
      grpc_port: 9000
