apiVersion: v1
kind: Service
metadata:
  name: {{ include "flipt.fullname" . }}
  labels:
    {{- include "flipt.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "flipt.selectorLabels" . | nindent 4 }}
