CREATE TABLE IF NOT EXISTS operation_lock (
  operation VARCHAR(255) PRIMARY KEY UNIQUE NOT NULL,
  version INTEGER DEFAULT 0 NOT NULL,
  last_acquired_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  acquired_until TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
