# action.yml
name: "Flipt IT Tests"
description: "Container for running Flipt ITs"
inputs:
  script: # id of input
    description: "script to run in the container"
    required: true
  config: # id of input
    description: "optional config file"
    required: false
runs:
  using: "docker"
  image: "docker://ghcr.io/flipt-io/flipt-integration-test"
  args:
    - ${{ inputs.script }}
    - ${{ inputs.config }}
