# action.yml
name: "Flipt IT Tests"
description: "Container for running Flipt ITs"
inputs:
  args: # id of input
    description: "args to pass to container"
    required: true
runs:
  using: "docker"
  image: "docker://ghcr.io/markphelps/flipt-integration-test:latest"
  pre-entrypoint: "npx playwright install chromium --with-deps" # install latest chromium with deps
  args:
    - ${{ inputs.args }}
