#!/bin/sh

go get github.com/grpc-ecosystem/grpc-gateway/v2@v2.7.0

TOOLS=$(pwd)/_tools
export GOBIN=$TOOLS/bin

mkdir -p _tools/bin
cd $TOOLS

if [ ! -f go.mod ]; then
    go mod init tools
fi

go install \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
    google.golang.org/protobuf/cmd/protoc-gen-go \
    google.golang.org/grpc/cmd/protoc-gen-go-grpc \
    github.com/golangci/golangci-lint/cmd/golangci-lint \
    golang.org/x/tools/cmd/cover \
    golang.org/x/tools/cmd/goimports \
    github.com/buchanae/github-release-notes
