#!/bin/sh

TOOLS=$(pwd)/_tools
export GOBIN=$TOOLS/bin

mkdir -p _tools/bin
cd $TOOLS

if [ ! -f go.mod ]; then
    go mod init tools
fi

go install \
    github.com/buchanae/github-release-notes \
    github.com/bufbuild/buf/cmd/buf \
    github.com/bufbuild/buf/cmd/protoc-gen-buf-breaking \
    github.com/bufbuild/buf/cmd/protoc-gen-buf-lint \
    github.com/cortesi/modd/cmd/modd \
    github.com/golangci/golangci-lint/cmd/golangci-lint \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
    github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
    golang.org/x/tools/cmd/cover \
    golang.org/x/tools/cmd/goimports \
    google.golang.org/grpc/cmd/protoc-gen-go-grpc \
    google.golang.org/protobuf/cmd/protoc-gen-go \
