#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")/.." || exit

case "$1" in
"release")
            github-release-notes -org markphelps -repo flipt --since-latest-release | tee release.out

            goreleaser --rm-dist --release-notes release.out

            rm release.out
            ;;

"snapshot")
            goreleaser --rm-dist --snapshot
            ;;

"clients")
            GO_OUTPUT_DIR=$(realpath "../flipt-grpc-go")
            RUBY_OUTPUT_DIR=$(realpath "../flipt-grpc-ruby/lib")

            if [[ -f "grpc_tools_ruby_protoc" ]]; then
                echo "--> installing ruby dependencies..."
                gem install grpc-tools
            fi

            echo "--> generating Go client to $GO_OUTPUT_DIR ..."

            protoc -I rpc/ rpc/flipt.proto --go_out=plugins=grpc:"$GO_OUTPUT_DIR" --go_opt=paths=source_relative

            echo "--> generating Ruby client to $RUBY_OUTPUT_DIR ..."

            grpc_tools_ruby_protoc -I rpc/ --ruby_out="$RUBY_OUTPUT_DIR" --grpc_out="$RUBY_OUTPUT_DIR" rpc/flipt.proto
            ;;
*)  echo "unknown command"
    ;;
esac
