#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")/.." || exit

case "$1" in
"release")
            goreleaser --rm-dist --release-notes <(github-release-notes -org markphelps -repo flipt --since-latest-release)
            ;;

"snapshot")
            goreleaser --rm-dist --snapshot
            ;;
*)  echo "unknown command"
    ;;
esac
