version: "3"

services:
  mysql:
    image: mysql:latest
    networks:
      - flipt_network
    environment:
      - MYSQL_DATABASE=flipt
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5

  flipt:
    image: flipt/flipt:latest
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - flipt_network
    environment:
      - FLIPT_DB_URL=mysql://mysql:password@mysql:3306/flipt
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_META_TELEMETRY_ENABLED=false
    command: ["/flipt", "--force-migrate"]

networks:
  flipt_network:
