version: "3.7"

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - flipt_network
    environment:
      - CLICKHOUSE_DB=flipt_analytics

  flipt:
    build: .
    depends_on:
      - clickhouse
    ports:
      - "8080:8080"
    networks:
      - flipt_network
    restart: always
    environment:
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_ANALYTICS_STORAGE_CLICKHOUSE_ENABLED=true
      - FLIPT_ANALYTICS_STORAGE_CLICKHOUSE_URL=clickhouse://clickhouse:9000/flipt_analytics
      - FLIPT_META_TELEMETRY_ENABLED=false
    command:
      [
        "./tmp/wait-for-it.sh",
        "clickhouse:9000",
        "--",
        "./flipt",
        "--force-migrate",
      ]

networks:
  flipt_network:
