version: "3.7"

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - flipt_network
    environment:
      - CLICKHOUSE_DB=flipt_analytics
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1

  flipt:
    image: flipt/flipt:latest
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - flipt_network
    restart: always
    environment:
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_ANALYTICS_STORAGE_CLICKHOUSE_ENABLED=true
      - FLIPT_ANALYTICS_STORAGE_CLICKHOUSE_URL=clickhouse://clickhouse:9000/flipt_analytics
      - FLIPT_META_TELEMETRY_ENABLED=false
    command: ["/flipt", "--force-migrate"]

networks:
  flipt_network:
