#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")/.." || exit

if [ ! -f "$GOPATH/bin/golangci-lint" ]; then \
    curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$GOPATH/bin" v1.12.5; \
fi

golangci-lint run
