#!/bin/bash

set -euo pipefail

GORELEASER_VERSION=v0.104

cd "$(dirname "$0")/.." || exit

read -r -p "Are you sure? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
then
  echo "==> Releasing with goreleaser"

  docker run --rm --privileged \
    -v "$PWD":/go/src/github.com/markphelps/flipt \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -w /go/src/github.com/markphelps/flipt \
    -e GITHUB_TOKEN \
    -e DOCKER_USERNAME \
    -e DOCKER_PASSWORD \
    goreleaser/goreleaser:"$GORELEASER_VERSION"-cgo --rm-dist

  echo "==> Publishing docs"
  mkdocs gh-deploy
fi
