#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")/.."

# usage: ./scripts/release [-r | --run ]
# defaults to dry-run which does not publish artifacts

GORELEASER_VERSION=v0.101
GORELEASER_ARGS="--snapshot --skip-publish"

while [ $# -gt 0 ]
do
key="$1"

case $key in
    -r|--run)
    GORELEASER_ARGS=""
    shift # past argument
    ;;
esac
done

docker run --rm --privileged \
  -v "$PWD":/go/src/github.com/markphelps/flipt \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -w /go/src/github.com/markphelps/flipt \
  -e GITHUB_TOKEN \
  -e DOCKER_USERNAME \
  -e DOCKER_PASSWORD \
  goreleaser/goreleaser:"$GORELEASER_VERSION"-cgo --rm-dist "$GORELEASER_ARGS"
