version: "3"

services:
  next:
    build: .
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_FLIPT_ADDR=http://localhost:8080
      - FLIPT_ADDR=http://flipt:8080
    depends_on:
      flipt:
        condition: service_healthy
    networks:
      - flipt_network

  init:
    image: flipt/flipt:latest
    command: ["./flipt", "import", "--skip-existing", "flipt.yml"]
    environment:
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_META_TELEMETRY_ENABLED=false
    volumes:
      - "./flipt.yml:/flipt.yml"
      - "flipt_data:/var/opt/flipt"

  flipt:
    image: flipt/flipt:latest
    command: ["./flipt", "--force-migrate"]
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_META_TELEMETRY_ENABLED=false
      - FLIPT_CORS_ENABLED=true
    volumes:
      - "flipt_data:/var/opt/flipt"
    networks:
      - flipt_network
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:8080/health || exit 1
      interval: 5s
      start_period: 5s

volumes:
  flipt_data:

networks:
  flipt_network:
