// Code generated by mockery v2.42.1. DO NOT EDIT.

package ecr

import (
	context "context"

	serviceecr "github.com/aws/aws-sdk-go-v2/service/ecr"
	mock "github.com/stretchr/testify/mock"
)

// MockPrivateClient is an autogenerated mock type for the PrivateClient type
type MockPrivateClient struct {
	mock.Mock
}

// GetAuthorizationToken provides a mock function with given fields: ctx, params, optFns
func (_m *MockPrivateClient) GetAuthorizationToken(ctx context.Context, params *serviceecr.GetAuthorizationTokenInput, optFns ...func(*serviceecr.Options)) (*serviceecr.GetAuthorizationTokenOutput, error) {
	_va := make([]interface{}, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorizationToken")
	}

	var r0 *serviceecr.GetAuthorizationTokenOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *serviceecr.GetAuthorizationTokenInput, ...func(*serviceecr.Options)) (*serviceecr.GetAuthorizationTokenOutput, error)); ok {
		return rf(ctx, params, optFns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *serviceecr.GetAuthorizationTokenInput, ...func(*serviceecr.Options)) *serviceecr.GetAuthorizationTokenOutput); ok {
		r0 = rf(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceecr.GetAuthorizationTokenOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *serviceecr.GetAuthorizationTokenInput, ...func(*serviceecr.Options)) error); ok {
		r1 = rf(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPrivateClient creates a new instance of MockPrivateClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrivateClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrivateClient {
	mock := &MockPrivateClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
