// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: flipt.proto

package flipt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Flipt_ListFlags_FullMethodName = "/flipt.Flipt/ListFlags"
)

// FliptClient is the client API for Flipt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FliptClient interface {
	ListFlags(ctx context.Context, in *ListFlagRequest, opts ...grpc.CallOption) (*FlagList, error)
}

type fliptClient struct {
	cc grpc.ClientConnInterface
}

func NewFliptClient(cc grpc.ClientConnInterface) FliptClient {
	return &fliptClient{cc}
}

func (c *fliptClient) ListFlags(ctx context.Context, in *ListFlagRequest, opts ...grpc.CallOption) (*FlagList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlagList)
	err := c.cc.Invoke(ctx, Flipt_ListFlags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FliptServer is the server API for Flipt service.
// All implementations must embed UnimplementedFliptServer
// for forward compatibility.
type FliptServer interface {
	ListFlags(context.Context, *ListFlagRequest) (*FlagList, error)
	mustEmbedUnimplementedFliptServer()
}

// UnimplementedFliptServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFliptServer struct{}

func (UnimplementedFliptServer) ListFlags(context.Context, *ListFlagRequest) (*FlagList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFlags not implemented")
}
func (UnimplementedFliptServer) mustEmbedUnimplementedFliptServer() {}
func (UnimplementedFliptServer) testEmbeddedByValue()               {}

// UnsafeFliptServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FliptServer will
// result in compilation errors.
type UnsafeFliptServer interface {
	mustEmbedUnimplementedFliptServer()
}

func RegisterFliptServer(s grpc.ServiceRegistrar, srv FliptServer) {
	// If the following call pancis, it indicates UnimplementedFliptServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Flipt_ServiceDesc, srv)
}

func _Flipt_ListFlags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFlagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FliptServer).ListFlags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Flipt_ListFlags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FliptServer).ListFlags(ctx, req.(*ListFlagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Flipt_ServiceDesc is the grpc.ServiceDesc for Flipt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Flipt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flipt.Flipt",
	HandlerType: (*FliptServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFlags",
			Handler:    _Flipt_ListFlags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flipt.proto",
}
