openapiOptions:
  file:
  - file: auth/auth.proto
    option:
      consumes:
      - application/json
      externalDocs:
        description: Flipt Docs
        url: https://www.flipt.io/docs
      info:
        contact:
          email: dev@flipt.io
          name: Flipt Team
          url: https://github.com/flipt-io/flipt
        license:
          name: MIT License
          url: https://github.com/flipt-io/flipt/blob/main/rpc/flipt/LICENSE
        title: Flipt Authentication APIs
        version: latest
      produces:
      - application/json
      responses:
        "401":
          description: Request could not be authenticated (authentication required).
          schema:
            jsonSchema:
              ref: '#/definitions/rpcStatus'
      schemes:
      - HTTP
      - HTTPS
      security:
      - securityRequirement:
          ClientTokenBearer: {}
      securityDefinitions:
        security:
          ClientTokenBearer:
            in: IN_HEADER
            name: Authorization
            type: TYPE_API_KEY
  - file: flipt.proto
    option:
      consumes:
      - application/json
      externalDocs:
        description: Flipt Docs
        url: https://www.flipt.io/docs
      info:
        contact:
          email: dev@flipt.io
          name: Flipt Team
          url: https://github.com/flipt-io/flipt
        license:
          name: MIT License
          url: https://github.com/flipt-io/flipt/blob/main/rpc/flipt/LICENSE
        title: Flipt API
        version: latest
      produces:
      - application/json
      responses:
        "401":
          description: Request could not be authenticated (authentication required).
          schema:
            jsonSchema:
              ref: '#/definitions/rpcStatus'
      schemes:
      - HTTP
      - HTTPS
      security:
      - securityRequirement:
          ClientTokenBearer: {}
      securityDefinitions:
        security:
          ClientTokenBearer:
            in: IN_HEADER
            name: Authorization
            type: TYPE_API_KEY
  - file: meta/meta.proto
    option:
      consumes:
      - application/json
      externalDocs:
        description: Flipt Docs
        url: https://www.flipt.io/docs
      info:
        contact:
          email: dev@flipt.io
          name: Flipt Team
          url: https://github.com/flipt-io/flipt
        license:
          name: MIT License
          url: https://github.com/flipt-io/flipt/blob/main/rpc/flipt/LICENSE
        title: Flipt Metadata APIs
        version: latest
      produces:
      - application/json
      responses:
        "401":
          description: Request could not be authenticated (authentication required).
          schema:
            jsonSchema:
              ref: '#/definitions/rpcStatus'
      schemes:
      - HTTP
      - HTTPS
      security:
      - securityRequirement:
          ClientTokenBearer: {}
      securityDefinitions:
        security:
          ClientTokenBearer:
            in: IN_HEADER
            name: Authorization
            type: TYPE_API_KEY
  message:
  - message: .flipt.auth.MethodInfo
  - message: .flipt.auth.ListAuthenticationMethodsResponse
  - message: .flipt.auth.Authentication
  - message: .flipt.auth.Authentication.MetadataEntry
  - message: .flipt.auth.GetAuthenticationRequest
    option:
      jsonSchema:
        required:
        - id
  - message: .flipt.auth.ListAuthenticationsRequest
  - message: .flipt.auth.ListAuthenticationsResponse
  - message: .flipt.auth.DeleteAuthenticationRequest
    option:
      jsonSchema:
        required:
        - id
  - message: .flipt.auth.ExpireAuthenticationSelfRequest
  - message: .flipt.auth.CreateTokenRequest
    option:
      jsonSchema:
        required:
        - name
        - description
  - message: .flipt.auth.CreateTokenResponse
  - message: .flipt.auth.AuthorizeURLRequest
  - message: .flipt.auth.AuthorizeURLResponse
  - message: .flipt.auth.CallbackRequest
  - message: .flipt.auth.CallbackResponse
  - message: .flipt.auth.VerifyServiceAccountRequest
  - message: .flipt.auth.VerifyServiceAccountResponse
  - message: .flipt.EvaluationRequest
    option:
      jsonSchema:
        required:
        - flag_key
        - entity_id
  - message: .flipt.EvaluationRequest.ContextEntry
  - message: .flipt.BatchEvaluationRequest
    option:
      jsonSchema:
        required:
        - requests
  - message: .flipt.EvaluationResponse
  - message: .flipt.EvaluationResponse.RequestContextEntry
  - message: .flipt.BatchEvaluationResponse
  - message: .flipt.Namespace
  - message: .flipt.NamespaceList
  - message: .flipt.GetNamespaceRequest
    option:
      jsonSchema:
        required:
        - key
  - message: .flipt.ListNamespaceRequest
  - message: .flipt.CreateNamespaceRequest
    option:
      jsonSchema:
        required:
        - key
        - name
  - message: .flipt.UpdateNamespaceRequest
    option:
      jsonSchema:
        required:
        - key
        - name
  - message: .flipt.DeleteNamespaceRequest
    option:
      jsonSchema:
        required:
        - key
  - message: .flipt.Flag
  - message: .flipt.FlagList
  - message: .flipt.GetFlagRequest
    option:
      jsonSchema:
        required:
        - key
  - message: .flipt.ListFlagRequest
  - message: .flipt.CreateFlagRequest
    option:
      jsonSchema:
        required:
        - key
        - name
  - message: .flipt.UpdateFlagRequest
    option:
      jsonSchema:
        required:
        - key
        - name
  - message: .flipt.DeleteFlagRequest
    option:
      jsonSchema:
        required:
        - key
  - message: .flipt.Variant
  - message: .flipt.CreateVariantRequest
    option:
      jsonSchema:
        required:
        - flag_key
        - key
  - message: .flipt.UpdateVariantRequest
    option:
      jsonSchema:
        required:
        - id
        - flag_key
        - key
  - message: .flipt.DeleteVariantRequest
    option:
      jsonSchema:
        required:
        - id
        - flag_key
  - message: .flipt.Segment
  - message: .flipt.SegmentList
  - message: .flipt.GetSegmentRequest
    option:
      jsonSchema:
        required:
        - key
  - message: .flipt.ListSegmentRequest
  - message: .flipt.CreateSegmentRequest
    option:
      jsonSchema:
        required:
        - key
        - name
  - message: .flipt.UpdateSegmentRequest
    option:
      jsonSchema:
        required:
        - key
        - name
  - message: .flipt.DeleteSegmentRequest
    option:
      jsonSchema:
        required:
        - key
  - message: .flipt.Constraint
  - message: .flipt.CreateConstraintRequest
    option:
      jsonSchema:
        required:
        - segment_key
        - type
        - property
        - operator
  - message: .flipt.UpdateConstraintRequest
    option:
      jsonSchema:
        required:
        - id
        - segment_key
        - type
        - property
        - operator
  - message: .flipt.DeleteConstraintRequest
    option:
      jsonSchema:
        required:
        - id
        - segment_key
  - message: .flipt.Rule
  - message: .flipt.RuleList
  - message: .flipt.ListRuleRequest
    option:
      jsonSchema:
        required:
        - flag_key
  - message: .flipt.GetRuleRequest
    option:
      jsonSchema:
        required:
        - id
        - flag_key
  - message: .flipt.CreateRuleRequest
    option:
      jsonSchema:
        required:
        - flag_key
        - segment_key
        - rank
  - message: .flipt.UpdateRuleRequest
    option:
      jsonSchema:
        required:
        - id
        - flag_key
        - segment_key
  - message: .flipt.DeleteRuleRequest
    option:
      jsonSchema:
        required:
        - id
        - flag_key
  - message: .flipt.OrderRulesRequest
    option:
      jsonSchema:
        required:
        - flag_key
        - rule_ids
  - message: .flipt.Distribution
  - message: .flipt.CreateDistributionRequest
    option:
      jsonSchema:
        required:
        - flag_key
        - rule_id
        - variant_id
        - rollout
  - message: .flipt.UpdateDistributionRequest
    option:
      jsonSchema:
        required:
        - id
        - flag_key
        - rule_id
        - variant_id
        - rollout
  - message: .flipt.DeleteDistributionRequest
    option:
      jsonSchema:
        required:
        - id
        - flag_key
        - rule_id
        - variant_id
  method:
  - method: .flipt.auth.PublicAuthenticationService.ListAuthenticationMethods
    option:
      description: List all available authentication methods
      operationId: list_authentication_methods
      tags:
      - authentication
  - method: .flipt.auth.AuthenticationService.GetAuthenticationSelf
    option:
      description: Get Authentication for current authenticated context
      operationId: get_self
      tags:
      - authentication
  - method: .flipt.auth.AuthenticationService.GetAuthentication
    option:
      description: Get Authentication by ID
      operationId: get_authentication
      tags:
      - authentication
  - method: .flipt.auth.AuthenticationService.ListAuthentications
    option:
      description: List Authentication instances
      operationId: list_authentications
      tags:
      - authentication
  - method: .flipt.auth.AuthenticationService.DeleteAuthentication
    option:
      description: Delete Authentication by ID
      operationId: delete_authentication
      tags:
      - authentication
  - method: .flipt.auth.AuthenticationService.ExpireAuthenticationSelf
    option:
      description: Expire Authentication for current authenticated context
      operationId: expire_self
      tags:
      - authentication
  - method: .flipt.auth.AuthenticationMethodTokenService.CreateToken
    option:
      description: Create authentication token
      operationId: create
      tags:
      - authentication authentication_method token
  - method: .flipt.auth.AuthenticationMethodOIDCService.AuthorizeURL
    option:
      description: Generate OIDC authorize URL
      operationId: authorize_url
      tags:
      - authentication authentication_method oidc
  - method: .flipt.auth.AuthenticationMethodOIDCService.Callback
    option:
      description: OIDC callback operation
      operationId: callback
      tags:
      - authentication authentication_method oidc
  - method: .flipt.auth.AuthenticationMethodKubernetesService.VerifyServiceAccount
    option:
      description: Verify service account token and exchange for client token
      operationId: verify_service_account
      tags:
      - authentication authentication_method kubernetes
  - method: .flipt.Flipt.Evaluate
    option:
      description: Evaluate
      operationId: evaluate
      tags:
      - evaluate
  - method: .flipt.Flipt.BatchEvaluate
    option:
      description: Batch Evaluate
      operationId: batchEvaluate
      tags:
      - evaluate
  - method: .flipt.Flipt.GetNamespace
    option:
      description: Get Namespace
      operationId: getNamespace
      tags:
      - namespaces
  - method: .flipt.Flipt.ListNamespaces
    option:
      description: List Namespaces
      operationId: listNamespaces
      tags:
      - namespaces
  - method: .flipt.Flipt.CreateNamespace
    option:
      description: Create Namespace
      operationId: createNamespace
      tags:
      - namespaces
  - method: .flipt.Flipt.UpdateNamespace
    option:
      description: Update Namespace
      operationId: updateNamespace
      tags:
      - namespaces
  - method: .flipt.Flipt.DeleteNamespace
    option:
      description: Delete Namespace
      operationId: deleteNamespace
      tags:
      - namespaces
  - method: .flipt.Flipt.GetFlag
    option:
      description: Get Flag
      operationId: getFlag
      tags:
      - flags
  - method: .flipt.Flipt.ListFlags
    option:
      description: List Flags
      operationId: listFlags
      tags:
      - flags
  - method: .flipt.Flipt.CreateFlag
    option:
      description: Create Flag
      operationId: createFlag
      tags:
      - flags
  - method: .flipt.Flipt.UpdateFlag
    option:
      description: Update Flag
      operationId: updateFlag
      tags:
      - flags
  - method: .flipt.Flipt.DeleteFlag
    option:
      description: Delete Flag
      operationId: deleteFlag
      tags:
      - flags
  - method: .flipt.Flipt.CreateVariant
    option:
      description: Create Variant
      operationId: createVariant
      tags:
      - variants
  - method: .flipt.Flipt.UpdateVariant
    option:
      description: Update Variant
      operationId: updateVariant
      tags:
      - variants
  - method: .flipt.Flipt.DeleteVariant
    option:
      description: Delete Variant
      operationId: deleteVariant
      tags:
      - variants
  - method: .flipt.Flipt.GetRule
    option:
      description: Get Rule
      operationId: getRule
      tags:
      - rules
  - method: .flipt.Flipt.ListRules
    option:
      description: List Rules
      operationId: listRules
      tags:
      - rules
  - method: .flipt.Flipt.CreateRule
    option:
      description: Create Rule
      operationId: createRule
      tags:
      - rules
  - method: .flipt.Flipt.UpdateRule
    option:
      description: Update Rule
      operationId: updateRule
      tags:
      - rules
  - method: .flipt.Flipt.OrderRules
    option:
      description: Order Rules
      operationId: orderRules
      tags:
      - rules
  - method: .flipt.Flipt.DeleteRule
    option:
      description: Delete Rule
      operationId: deleteRule
      tags:
      - rules
  - method: .flipt.Flipt.CreateDistribution
    option:
      description: Create Distribution
      operationId: createDistribution
      tags:
      - distributions
  - method: .flipt.Flipt.UpdateDistribution
    option:
      description: Update Distribution
      operationId: updateDistribution
      tags:
      - distributions
  - method: .flipt.Flipt.DeleteDistribution
    option:
      description: Delete Distribution
      operationId: deleteDistribution
      tags:
      - distributions
  - method: .flipt.Flipt.GetSegment
    option:
      description: Get Segment
      operationId: getSegment
      tags:
      - segments
  - method: .flipt.Flipt.ListSegments
    option:
      description: List Segments
      operationId: listSegments
      tags:
      - segments
  - method: .flipt.Flipt.CreateSegment
    option:
      description: Create Segment
      operationId: createSegment
      tags:
      - segments
  - method: .flipt.Flipt.UpdateSegment
    option:
      description: Update Segment
      operationId: updateSegment
      tags:
      - segments
  - method: .flipt.Flipt.DeleteSegment
    option:
      description: Delete Segment
      operationId: deleteSegment
      tags:
      - segments
  - method: .flipt.Flipt.CreateConstraint
    option:
      description: Create Constraint
      operationId: createConstraint
      tags:
      - constraints
  - method: .flipt.Flipt.UpdateConstraint
    option:
      description: Update Constraint
      operationId: updateConstraint
      tags:
      - constraints
  - method: .flipt.Flipt.DeleteConstraint
    option:
      description: Delete Constraint
      operationId: deleteConstraint
      tags:
      - constraints
  - method: .flipt.meta.MetadataService.GetConfiguration
    option:
      description: Get Flipt instance configuration.
      operationId: get_configuration
      tags:
      - metadata
  - method: .flipt.meta.MetadataService.GetInfo
    option:
      description: Get Flipt instance information.
      operationId: get_info
      tags:
      - metadata
