version: "3"

services:
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - "9411:9411"
    networks:
      - flipt_network

  flipt:
    image: flipt/flipt:latest
    command: ["./flipt", "--force-migrate"]
    depends_on:
      - zipkin
    ports:
      - "8080:8080"
    networks:
      - flipt_network
    environment:
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_TRACING_ENABLED=true
      - FLIPT_TRACING_EXPORTER=zipkin
      - FLIPT_TRACING_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - FLIPT_META_TELMETRY_ENABLED=false

networks:
  flipt_network:
