version: "3"

services:
  postgres:
    image: postgres:12
    networks:
      - flipt_network
    environment:
      - POSTGRES_DB=flipt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  flipt:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - flipt_network
    environment:
      - FLIPT_DB_URL=postgres://postgres:password@postgres:5432/flipt?sslmode=disable
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_META_TELEMETRY_ENABLED=false
    command: ["./tmp/wait-for-it.sh", "postgres:5432", "--", "./flipt", "--force-migrate"]

networks:
  flipt_network:
