version: "3"

services:
  flipt:
    image: flipt/flipt:latest
    command: ["./flipt", "--force-migrate"]
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/etc/flipt/config/default.yml
    environment:
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_META_TELEMETRY_ENABLED=false
    networks:
      - flipt_network

networks:
  flipt_network:
