version: "3"

services:
  proxy:
    image: caddy:latest
    ports:
      - "8081:8081"
    networks:
      - flipt_network
    volumes:
      - "${PWD}/Caddyfile:/etc/caddy/Caddyfile"

  next:
    build: .
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    environment:
      - FLIPT_PUBLIC_ADDR=http://proxy:8081
      - FLIPT_ADDR=http://flipt:8080
    depends_on:
      - proxy
      - flipt
    networks:
      - flipt_network

  init:
    image: flipt/flipt:latest
    command: ["./flipt", "import", "flipt.yml"]
    environment:
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_META_TELEMETRY_ENABLED=false
    volumes:
      - "./flipt.yml:/flipt.yml"
      - "flipt_data:/var/opt/flipt"

  flipt:
    image: flipt/flipt:latest
    command: ["./flipt"]
    depends_on:
      - init
    ports:
      - "8080:8080"
    environment:
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_META_TELEMETRY_ENABLED=false
    volumes:
      - "flipt_data:/var/opt/flipt"
    networks:
      - flipt_network

volumes:
  flipt_data:

networks:
  flipt_network:
