// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package common

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.flipt.io/flipt/internal/storage"
	"go.flipt.io/flipt/rpc/flipt"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// CountFlags provides a mock function for the type MockStore
func (_mock *MockStore) CountFlags(ctx context.Context, ns storage.NamespaceRequest) (uint64, error) {
	ret := _mock.Called(ctx, ns)

	if len(ret) == 0 {
		panic("no return value specified for CountFlags")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.NamespaceRequest) (uint64, error)); ok {
		return returnFunc(ctx, ns)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.NamespaceRequest) uint64); ok {
		r0 = returnFunc(ctx, ns)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.NamespaceRequest) error); ok {
		r1 = returnFunc(ctx, ns)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CountFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountFlags'
type MockStore_CountFlags_Call struct {
	*mock.Call
}

// CountFlags is a helper method to define mock.On call
//   - ctx context.Context
//   - ns storage.NamespaceRequest
func (_e *MockStore_Expecter) CountFlags(ctx interface{}, ns interface{}) *MockStore_CountFlags_Call {
	return &MockStore_CountFlags_Call{Call: _e.mock.On("CountFlags", ctx, ns)}
}

func (_c *MockStore_CountFlags_Call) Run(run func(ctx context.Context, ns storage.NamespaceRequest)) *MockStore_CountFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.NamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(storage.NamespaceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CountFlags_Call) Return(v uint64, err error) *MockStore_CountFlags_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockStore_CountFlags_Call) RunAndReturn(run func(ctx context.Context, ns storage.NamespaceRequest) (uint64, error)) *MockStore_CountFlags_Call {
	_c.Call.Return(run)
	return _c
}

// CountNamespaces provides a mock function for the type MockStore
func (_mock *MockStore) CountNamespaces(ctx context.Context, req storage.ReferenceRequest) (uint64, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CountNamespaces")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ReferenceRequest) (uint64, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ReferenceRequest) uint64); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.ReferenceRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CountNamespaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountNamespaces'
type MockStore_CountNamespaces_Call struct {
	*mock.Call
}

// CountNamespaces is a helper method to define mock.On call
//   - ctx context.Context
//   - req storage.ReferenceRequest
func (_e *MockStore_Expecter) CountNamespaces(ctx interface{}, req interface{}) *MockStore_CountNamespaces_Call {
	return &MockStore_CountNamespaces_Call{Call: _e.mock.On("CountNamespaces", ctx, req)}
}

func (_c *MockStore_CountNamespaces_Call) Run(run func(ctx context.Context, req storage.ReferenceRequest)) *MockStore_CountNamespaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.ReferenceRequest
		if args[1] != nil {
			arg1 = args[1].(storage.ReferenceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CountNamespaces_Call) Return(v uint64, err error) *MockStore_CountNamespaces_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockStore_CountNamespaces_Call) RunAndReturn(run func(ctx context.Context, req storage.ReferenceRequest) (uint64, error)) *MockStore_CountNamespaces_Call {
	_c.Call.Return(run)
	return _c
}

// CountRollouts provides a mock function for the type MockStore
func (_mock *MockStore) CountRollouts(ctx context.Context, flag storage.ResourceRequest) (uint64, error) {
	ret := _mock.Called(ctx, flag)

	if len(ret) == 0 {
		panic("no return value specified for CountRollouts")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ResourceRequest) (uint64, error)); ok {
		return returnFunc(ctx, flag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ResourceRequest) uint64); ok {
		r0 = returnFunc(ctx, flag)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.ResourceRequest) error); ok {
		r1 = returnFunc(ctx, flag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CountRollouts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountRollouts'
type MockStore_CountRollouts_Call struct {
	*mock.Call
}

// CountRollouts is a helper method to define mock.On call
//   - ctx context.Context
//   - flag storage.ResourceRequest
func (_e *MockStore_Expecter) CountRollouts(ctx interface{}, flag interface{}) *MockStore_CountRollouts_Call {
	return &MockStore_CountRollouts_Call{Call: _e.mock.On("CountRollouts", ctx, flag)}
}

func (_c *MockStore_CountRollouts_Call) Run(run func(ctx context.Context, flag storage.ResourceRequest)) *MockStore_CountRollouts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.ResourceRequest
		if args[1] != nil {
			arg1 = args[1].(storage.ResourceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CountRollouts_Call) Return(v uint64, err error) *MockStore_CountRollouts_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockStore_CountRollouts_Call) RunAndReturn(run func(ctx context.Context, flag storage.ResourceRequest) (uint64, error)) *MockStore_CountRollouts_Call {
	_c.Call.Return(run)
	return _c
}

// CountRules provides a mock function for the type MockStore
func (_mock *MockStore) CountRules(ctx context.Context, flag storage.ResourceRequest) (uint64, error) {
	ret := _mock.Called(ctx, flag)

	if len(ret) == 0 {
		panic("no return value specified for CountRules")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ResourceRequest) (uint64, error)); ok {
		return returnFunc(ctx, flag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ResourceRequest) uint64); ok {
		r0 = returnFunc(ctx, flag)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.ResourceRequest) error); ok {
		r1 = returnFunc(ctx, flag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CountRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountRules'
type MockStore_CountRules_Call struct {
	*mock.Call
}

// CountRules is a helper method to define mock.On call
//   - ctx context.Context
//   - flag storage.ResourceRequest
func (_e *MockStore_Expecter) CountRules(ctx interface{}, flag interface{}) *MockStore_CountRules_Call {
	return &MockStore_CountRules_Call{Call: _e.mock.On("CountRules", ctx, flag)}
}

func (_c *MockStore_CountRules_Call) Run(run func(ctx context.Context, flag storage.ResourceRequest)) *MockStore_CountRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.ResourceRequest
		if args[1] != nil {
			arg1 = args[1].(storage.ResourceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CountRules_Call) Return(v uint64, err error) *MockStore_CountRules_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockStore_CountRules_Call) RunAndReturn(run func(ctx context.Context, flag storage.ResourceRequest) (uint64, error)) *MockStore_CountRules_Call {
	_c.Call.Return(run)
	return _c
}

// CountSegments provides a mock function for the type MockStore
func (_mock *MockStore) CountSegments(ctx context.Context, ns storage.NamespaceRequest) (uint64, error) {
	ret := _mock.Called(ctx, ns)

	if len(ret) == 0 {
		panic("no return value specified for CountSegments")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.NamespaceRequest) (uint64, error)); ok {
		return returnFunc(ctx, ns)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.NamespaceRequest) uint64); ok {
		r0 = returnFunc(ctx, ns)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.NamespaceRequest) error); ok {
		r1 = returnFunc(ctx, ns)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CountSegments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSegments'
type MockStore_CountSegments_Call struct {
	*mock.Call
}

// CountSegments is a helper method to define mock.On call
//   - ctx context.Context
//   - ns storage.NamespaceRequest
func (_e *MockStore_Expecter) CountSegments(ctx interface{}, ns interface{}) *MockStore_CountSegments_Call {
	return &MockStore_CountSegments_Call{Call: _e.mock.On("CountSegments", ctx, ns)}
}

func (_c *MockStore_CountSegments_Call) Run(run func(ctx context.Context, ns storage.NamespaceRequest)) *MockStore_CountSegments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.NamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(storage.NamespaceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CountSegments_Call) Return(v uint64, err error) *MockStore_CountSegments_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockStore_CountSegments_Call) RunAndReturn(run func(ctx context.Context, ns storage.NamespaceRequest) (uint64, error)) *MockStore_CountSegments_Call {
	_c.Call.Return(run)
	return _c
}

// CreateConstraint provides a mock function for the type MockStore
func (_mock *MockStore) CreateConstraint(ctx context.Context, r *flipt.CreateConstraintRequest) (*flipt.Constraint, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreateConstraint")
	}

	var r0 *flipt.Constraint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateConstraintRequest) (*flipt.Constraint, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateConstraintRequest) *flipt.Constraint); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Constraint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.CreateConstraintRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateConstraint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConstraint'
type MockStore_CreateConstraint_Call struct {
	*mock.Call
}

// CreateConstraint is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.CreateConstraintRequest
func (_e *MockStore_Expecter) CreateConstraint(ctx interface{}, r interface{}) *MockStore_CreateConstraint_Call {
	return &MockStore_CreateConstraint_Call{Call: _e.mock.On("CreateConstraint", ctx, r)}
}

func (_c *MockStore_CreateConstraint_Call) Run(run func(ctx context.Context, r *flipt.CreateConstraintRequest)) *MockStore_CreateConstraint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.CreateConstraintRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.CreateConstraintRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateConstraint_Call) Return(constraint *flipt.Constraint, err error) *MockStore_CreateConstraint_Call {
	_c.Call.Return(constraint, err)
	return _c
}

func (_c *MockStore_CreateConstraint_Call) RunAndReturn(run func(ctx context.Context, r *flipt.CreateConstraintRequest) (*flipt.Constraint, error)) *MockStore_CreateConstraint_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDistribution provides a mock function for the type MockStore
func (_mock *MockStore) CreateDistribution(ctx context.Context, r *flipt.CreateDistributionRequest) (*flipt.Distribution, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreateDistribution")
	}

	var r0 *flipt.Distribution
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateDistributionRequest) (*flipt.Distribution, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateDistributionRequest) *flipt.Distribution); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Distribution)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.CreateDistributionRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDistribution'
type MockStore_CreateDistribution_Call struct {
	*mock.Call
}

// CreateDistribution is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.CreateDistributionRequest
func (_e *MockStore_Expecter) CreateDistribution(ctx interface{}, r interface{}) *MockStore_CreateDistribution_Call {
	return &MockStore_CreateDistribution_Call{Call: _e.mock.On("CreateDistribution", ctx, r)}
}

func (_c *MockStore_CreateDistribution_Call) Run(run func(ctx context.Context, r *flipt.CreateDistributionRequest)) *MockStore_CreateDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.CreateDistributionRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.CreateDistributionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateDistribution_Call) Return(distribution *flipt.Distribution, err error) *MockStore_CreateDistribution_Call {
	_c.Call.Return(distribution, err)
	return _c
}

func (_c *MockStore_CreateDistribution_Call) RunAndReturn(run func(ctx context.Context, r *flipt.CreateDistributionRequest) (*flipt.Distribution, error)) *MockStore_CreateDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFlag provides a mock function for the type MockStore
func (_mock *MockStore) CreateFlag(ctx context.Context, r *flipt.CreateFlagRequest) (*flipt.Flag, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreateFlag")
	}

	var r0 *flipt.Flag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateFlagRequest) (*flipt.Flag, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateFlagRequest) *flipt.Flag); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Flag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.CreateFlagRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFlag'
type MockStore_CreateFlag_Call struct {
	*mock.Call
}

// CreateFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.CreateFlagRequest
func (_e *MockStore_Expecter) CreateFlag(ctx interface{}, r interface{}) *MockStore_CreateFlag_Call {
	return &MockStore_CreateFlag_Call{Call: _e.mock.On("CreateFlag", ctx, r)}
}

func (_c *MockStore_CreateFlag_Call) Run(run func(ctx context.Context, r *flipt.CreateFlagRequest)) *MockStore_CreateFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.CreateFlagRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.CreateFlagRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateFlag_Call) Return(flag *flipt.Flag, err error) *MockStore_CreateFlag_Call {
	_c.Call.Return(flag, err)
	return _c
}

func (_c *MockStore_CreateFlag_Call) RunAndReturn(run func(ctx context.Context, r *flipt.CreateFlagRequest) (*flipt.Flag, error)) *MockStore_CreateFlag_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNamespace provides a mock function for the type MockStore
func (_mock *MockStore) CreateNamespace(ctx context.Context, r *flipt.CreateNamespaceRequest) (*flipt.Namespace, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreateNamespace")
	}

	var r0 *flipt.Namespace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateNamespaceRequest) (*flipt.Namespace, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateNamespaceRequest) *flipt.Namespace); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Namespace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.CreateNamespaceRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNamespace'
type MockStore_CreateNamespace_Call struct {
	*mock.Call
}

// CreateNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.CreateNamespaceRequest
func (_e *MockStore_Expecter) CreateNamespace(ctx interface{}, r interface{}) *MockStore_CreateNamespace_Call {
	return &MockStore_CreateNamespace_Call{Call: _e.mock.On("CreateNamespace", ctx, r)}
}

func (_c *MockStore_CreateNamespace_Call) Run(run func(ctx context.Context, r *flipt.CreateNamespaceRequest)) *MockStore_CreateNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.CreateNamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.CreateNamespaceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateNamespace_Call) Return(namespace *flipt.Namespace, err error) *MockStore_CreateNamespace_Call {
	_c.Call.Return(namespace, err)
	return _c
}

func (_c *MockStore_CreateNamespace_Call) RunAndReturn(run func(ctx context.Context, r *flipt.CreateNamespaceRequest) (*flipt.Namespace, error)) *MockStore_CreateNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRollout provides a mock function for the type MockStore
func (_mock *MockStore) CreateRollout(ctx context.Context, r *flipt.CreateRolloutRequest) (*flipt.Rollout, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreateRollout")
	}

	var r0 *flipt.Rollout
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateRolloutRequest) (*flipt.Rollout, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateRolloutRequest) *flipt.Rollout); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Rollout)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.CreateRolloutRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateRollout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRollout'
type MockStore_CreateRollout_Call struct {
	*mock.Call
}

// CreateRollout is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.CreateRolloutRequest
func (_e *MockStore_Expecter) CreateRollout(ctx interface{}, r interface{}) *MockStore_CreateRollout_Call {
	return &MockStore_CreateRollout_Call{Call: _e.mock.On("CreateRollout", ctx, r)}
}

func (_c *MockStore_CreateRollout_Call) Run(run func(ctx context.Context, r *flipt.CreateRolloutRequest)) *MockStore_CreateRollout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.CreateRolloutRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.CreateRolloutRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateRollout_Call) Return(rollout *flipt.Rollout, err error) *MockStore_CreateRollout_Call {
	_c.Call.Return(rollout, err)
	return _c
}

func (_c *MockStore_CreateRollout_Call) RunAndReturn(run func(ctx context.Context, r *flipt.CreateRolloutRequest) (*flipt.Rollout, error)) *MockStore_CreateRollout_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRule provides a mock function for the type MockStore
func (_mock *MockStore) CreateRule(ctx context.Context, r *flipt.CreateRuleRequest) (*flipt.Rule, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreateRule")
	}

	var r0 *flipt.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateRuleRequest) (*flipt.Rule, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateRuleRequest) *flipt.Rule); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Rule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.CreateRuleRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRule'
type MockStore_CreateRule_Call struct {
	*mock.Call
}

// CreateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.CreateRuleRequest
func (_e *MockStore_Expecter) CreateRule(ctx interface{}, r interface{}) *MockStore_CreateRule_Call {
	return &MockStore_CreateRule_Call{Call: _e.mock.On("CreateRule", ctx, r)}
}

func (_c *MockStore_CreateRule_Call) Run(run func(ctx context.Context, r *flipt.CreateRuleRequest)) *MockStore_CreateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.CreateRuleRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.CreateRuleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateRule_Call) Return(rule *flipt.Rule, err error) *MockStore_CreateRule_Call {
	_c.Call.Return(rule, err)
	return _c
}

func (_c *MockStore_CreateRule_Call) RunAndReturn(run func(ctx context.Context, r *flipt.CreateRuleRequest) (*flipt.Rule, error)) *MockStore_CreateRule_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSegment provides a mock function for the type MockStore
func (_mock *MockStore) CreateSegment(ctx context.Context, r *flipt.CreateSegmentRequest) (*flipt.Segment, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreateSegment")
	}

	var r0 *flipt.Segment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateSegmentRequest) (*flipt.Segment, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateSegmentRequest) *flipt.Segment); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Segment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.CreateSegmentRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateSegment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSegment'
type MockStore_CreateSegment_Call struct {
	*mock.Call
}

// CreateSegment is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.CreateSegmentRequest
func (_e *MockStore_Expecter) CreateSegment(ctx interface{}, r interface{}) *MockStore_CreateSegment_Call {
	return &MockStore_CreateSegment_Call{Call: _e.mock.On("CreateSegment", ctx, r)}
}

func (_c *MockStore_CreateSegment_Call) Run(run func(ctx context.Context, r *flipt.CreateSegmentRequest)) *MockStore_CreateSegment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.CreateSegmentRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.CreateSegmentRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateSegment_Call) Return(segment *flipt.Segment, err error) *MockStore_CreateSegment_Call {
	_c.Call.Return(segment, err)
	return _c
}

func (_c *MockStore_CreateSegment_Call) RunAndReturn(run func(ctx context.Context, r *flipt.CreateSegmentRequest) (*flipt.Segment, error)) *MockStore_CreateSegment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVariant provides a mock function for the type MockStore
func (_mock *MockStore) CreateVariant(ctx context.Context, r *flipt.CreateVariantRequest) (*flipt.Variant, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for CreateVariant")
	}

	var r0 *flipt.Variant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateVariantRequest) (*flipt.Variant, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.CreateVariantRequest) *flipt.Variant); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Variant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.CreateVariantRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateVariant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVariant'
type MockStore_CreateVariant_Call struct {
	*mock.Call
}

// CreateVariant is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.CreateVariantRequest
func (_e *MockStore_Expecter) CreateVariant(ctx interface{}, r interface{}) *MockStore_CreateVariant_Call {
	return &MockStore_CreateVariant_Call{Call: _e.mock.On("CreateVariant", ctx, r)}
}

func (_c *MockStore_CreateVariant_Call) Run(run func(ctx context.Context, r *flipt.CreateVariantRequest)) *MockStore_CreateVariant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.CreateVariantRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.CreateVariantRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateVariant_Call) Return(variant *flipt.Variant, err error) *MockStore_CreateVariant_Call {
	_c.Call.Return(variant, err)
	return _c
}

func (_c *MockStore_CreateVariant_Call) RunAndReturn(run func(ctx context.Context, r *flipt.CreateVariantRequest) (*flipt.Variant, error)) *MockStore_CreateVariant_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteConstraint provides a mock function for the type MockStore
func (_mock *MockStore) DeleteConstraint(ctx context.Context, r *flipt.DeleteConstraintRequest) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for DeleteConstraint")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.DeleteConstraintRequest) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteConstraint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteConstraint'
type MockStore_DeleteConstraint_Call struct {
	*mock.Call
}

// DeleteConstraint is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.DeleteConstraintRequest
func (_e *MockStore_Expecter) DeleteConstraint(ctx interface{}, r interface{}) *MockStore_DeleteConstraint_Call {
	return &MockStore_DeleteConstraint_Call{Call: _e.mock.On("DeleteConstraint", ctx, r)}
}

func (_c *MockStore_DeleteConstraint_Call) Run(run func(ctx context.Context, r *flipt.DeleteConstraintRequest)) *MockStore_DeleteConstraint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.DeleteConstraintRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.DeleteConstraintRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_DeleteConstraint_Call) Return(err error) *MockStore_DeleteConstraint_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteConstraint_Call) RunAndReturn(run func(ctx context.Context, r *flipt.DeleteConstraintRequest) error) *MockStore_DeleteConstraint_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDistribution provides a mock function for the type MockStore
func (_mock *MockStore) DeleteDistribution(ctx context.Context, r *flipt.DeleteDistributionRequest) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDistribution")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.DeleteDistributionRequest) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDistribution'
type MockStore_DeleteDistribution_Call struct {
	*mock.Call
}

// DeleteDistribution is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.DeleteDistributionRequest
func (_e *MockStore_Expecter) DeleteDistribution(ctx interface{}, r interface{}) *MockStore_DeleteDistribution_Call {
	return &MockStore_DeleteDistribution_Call{Call: _e.mock.On("DeleteDistribution", ctx, r)}
}

func (_c *MockStore_DeleteDistribution_Call) Run(run func(ctx context.Context, r *flipt.DeleteDistributionRequest)) *MockStore_DeleteDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.DeleteDistributionRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.DeleteDistributionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_DeleteDistribution_Call) Return(err error) *MockStore_DeleteDistribution_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteDistribution_Call) RunAndReturn(run func(ctx context.Context, r *flipt.DeleteDistributionRequest) error) *MockStore_DeleteDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFlag provides a mock function for the type MockStore
func (_mock *MockStore) DeleteFlag(ctx context.Context, r *flipt.DeleteFlagRequest) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFlag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.DeleteFlagRequest) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFlag'
type MockStore_DeleteFlag_Call struct {
	*mock.Call
}

// DeleteFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.DeleteFlagRequest
func (_e *MockStore_Expecter) DeleteFlag(ctx interface{}, r interface{}) *MockStore_DeleteFlag_Call {
	return &MockStore_DeleteFlag_Call{Call: _e.mock.On("DeleteFlag", ctx, r)}
}

func (_c *MockStore_DeleteFlag_Call) Run(run func(ctx context.Context, r *flipt.DeleteFlagRequest)) *MockStore_DeleteFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.DeleteFlagRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.DeleteFlagRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_DeleteFlag_Call) Return(err error) *MockStore_DeleteFlag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteFlag_Call) RunAndReturn(run func(ctx context.Context, r *flipt.DeleteFlagRequest) error) *MockStore_DeleteFlag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNamespace provides a mock function for the type MockStore
func (_mock *MockStore) DeleteNamespace(ctx context.Context, r *flipt.DeleteNamespaceRequest) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNamespace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.DeleteNamespaceRequest) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNamespace'
type MockStore_DeleteNamespace_Call struct {
	*mock.Call
}

// DeleteNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.DeleteNamespaceRequest
func (_e *MockStore_Expecter) DeleteNamespace(ctx interface{}, r interface{}) *MockStore_DeleteNamespace_Call {
	return &MockStore_DeleteNamespace_Call{Call: _e.mock.On("DeleteNamespace", ctx, r)}
}

func (_c *MockStore_DeleteNamespace_Call) Run(run func(ctx context.Context, r *flipt.DeleteNamespaceRequest)) *MockStore_DeleteNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.DeleteNamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.DeleteNamespaceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_DeleteNamespace_Call) Return(err error) *MockStore_DeleteNamespace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteNamespace_Call) RunAndReturn(run func(ctx context.Context, r *flipt.DeleteNamespaceRequest) error) *MockStore_DeleteNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRollout provides a mock function for the type MockStore
func (_mock *MockStore) DeleteRollout(ctx context.Context, r *flipt.DeleteRolloutRequest) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRollout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.DeleteRolloutRequest) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteRollout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRollout'
type MockStore_DeleteRollout_Call struct {
	*mock.Call
}

// DeleteRollout is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.DeleteRolloutRequest
func (_e *MockStore_Expecter) DeleteRollout(ctx interface{}, r interface{}) *MockStore_DeleteRollout_Call {
	return &MockStore_DeleteRollout_Call{Call: _e.mock.On("DeleteRollout", ctx, r)}
}

func (_c *MockStore_DeleteRollout_Call) Run(run func(ctx context.Context, r *flipt.DeleteRolloutRequest)) *MockStore_DeleteRollout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.DeleteRolloutRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.DeleteRolloutRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_DeleteRollout_Call) Return(err error) *MockStore_DeleteRollout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteRollout_Call) RunAndReturn(run func(ctx context.Context, r *flipt.DeleteRolloutRequest) error) *MockStore_DeleteRollout_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRule provides a mock function for the type MockStore
func (_mock *MockStore) DeleteRule(ctx context.Context, r *flipt.DeleteRuleRequest) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.DeleteRuleRequest) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRule'
type MockStore_DeleteRule_Call struct {
	*mock.Call
}

// DeleteRule is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.DeleteRuleRequest
func (_e *MockStore_Expecter) DeleteRule(ctx interface{}, r interface{}) *MockStore_DeleteRule_Call {
	return &MockStore_DeleteRule_Call{Call: _e.mock.On("DeleteRule", ctx, r)}
}

func (_c *MockStore_DeleteRule_Call) Run(run func(ctx context.Context, r *flipt.DeleteRuleRequest)) *MockStore_DeleteRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.DeleteRuleRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.DeleteRuleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_DeleteRule_Call) Return(err error) *MockStore_DeleteRule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteRule_Call) RunAndReturn(run func(ctx context.Context, r *flipt.DeleteRuleRequest) error) *MockStore_DeleteRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSegment provides a mock function for the type MockStore
func (_mock *MockStore) DeleteSegment(ctx context.Context, r *flipt.DeleteSegmentRequest) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSegment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.DeleteSegmentRequest) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteSegment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSegment'
type MockStore_DeleteSegment_Call struct {
	*mock.Call
}

// DeleteSegment is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.DeleteSegmentRequest
func (_e *MockStore_Expecter) DeleteSegment(ctx interface{}, r interface{}) *MockStore_DeleteSegment_Call {
	return &MockStore_DeleteSegment_Call{Call: _e.mock.On("DeleteSegment", ctx, r)}
}

func (_c *MockStore_DeleteSegment_Call) Run(run func(ctx context.Context, r *flipt.DeleteSegmentRequest)) *MockStore_DeleteSegment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.DeleteSegmentRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.DeleteSegmentRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_DeleteSegment_Call) Return(err error) *MockStore_DeleteSegment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteSegment_Call) RunAndReturn(run func(ctx context.Context, r *flipt.DeleteSegmentRequest) error) *MockStore_DeleteSegment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVariant provides a mock function for the type MockStore
func (_mock *MockStore) DeleteVariant(ctx context.Context, r *flipt.DeleteVariantRequest) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVariant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.DeleteVariantRequest) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteVariant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVariant'
type MockStore_DeleteVariant_Call struct {
	*mock.Call
}

// DeleteVariant is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.DeleteVariantRequest
func (_e *MockStore_Expecter) DeleteVariant(ctx interface{}, r interface{}) *MockStore_DeleteVariant_Call {
	return &MockStore_DeleteVariant_Call{Call: _e.mock.On("DeleteVariant", ctx, r)}
}

func (_c *MockStore_DeleteVariant_Call) Run(run func(ctx context.Context, r *flipt.DeleteVariantRequest)) *MockStore_DeleteVariant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.DeleteVariantRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.DeleteVariantRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_DeleteVariant_Call) Return(err error) *MockStore_DeleteVariant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteVariant_Call) RunAndReturn(run func(ctx context.Context, r *flipt.DeleteVariantRequest) error) *MockStore_DeleteVariant_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvaluationDistributions provides a mock function for the type MockStore
func (_mock *MockStore) GetEvaluationDistributions(ctx context.Context, flag storage.ResourceRequest, rule storage.IDRequest) ([]*storage.EvaluationDistribution, error) {
	ret := _mock.Called(ctx, flag, rule)

	if len(ret) == 0 {
		panic("no return value specified for GetEvaluationDistributions")
	}

	var r0 []*storage.EvaluationDistribution
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ResourceRequest, storage.IDRequest) ([]*storage.EvaluationDistribution, error)); ok {
		return returnFunc(ctx, flag, rule)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ResourceRequest, storage.IDRequest) []*storage.EvaluationDistribution); ok {
		r0 = returnFunc(ctx, flag, rule)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.EvaluationDistribution)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.ResourceRequest, storage.IDRequest) error); ok {
		r1 = returnFunc(ctx, flag, rule)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetEvaluationDistributions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvaluationDistributions'
type MockStore_GetEvaluationDistributions_Call struct {
	*mock.Call
}

// GetEvaluationDistributions is a helper method to define mock.On call
//   - ctx context.Context
//   - flag storage.ResourceRequest
//   - rule storage.IDRequest
func (_e *MockStore_Expecter) GetEvaluationDistributions(ctx interface{}, flag interface{}, rule interface{}) *MockStore_GetEvaluationDistributions_Call {
	return &MockStore_GetEvaluationDistributions_Call{Call: _e.mock.On("GetEvaluationDistributions", ctx, flag, rule)}
}

func (_c *MockStore_GetEvaluationDistributions_Call) Run(run func(ctx context.Context, flag storage.ResourceRequest, rule storage.IDRequest)) *MockStore_GetEvaluationDistributions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.ResourceRequest
		if args[1] != nil {
			arg1 = args[1].(storage.ResourceRequest)
		}
		var arg2 storage.IDRequest
		if args[2] != nil {
			arg2 = args[2].(storage.IDRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_GetEvaluationDistributions_Call) Return(evaluationDistributions []*storage.EvaluationDistribution, err error) *MockStore_GetEvaluationDistributions_Call {
	_c.Call.Return(evaluationDistributions, err)
	return _c
}

func (_c *MockStore_GetEvaluationDistributions_Call) RunAndReturn(run func(ctx context.Context, flag storage.ResourceRequest, rule storage.IDRequest) ([]*storage.EvaluationDistribution, error)) *MockStore_GetEvaluationDistributions_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvaluationRollouts provides a mock function for the type MockStore
func (_mock *MockStore) GetEvaluationRollouts(ctx context.Context, flag storage.ResourceRequest) ([]*storage.EvaluationRollout, error) {
	ret := _mock.Called(ctx, flag)

	if len(ret) == 0 {
		panic("no return value specified for GetEvaluationRollouts")
	}

	var r0 []*storage.EvaluationRollout
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ResourceRequest) ([]*storage.EvaluationRollout, error)); ok {
		return returnFunc(ctx, flag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ResourceRequest) []*storage.EvaluationRollout); ok {
		r0 = returnFunc(ctx, flag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.EvaluationRollout)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.ResourceRequest) error); ok {
		r1 = returnFunc(ctx, flag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetEvaluationRollouts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvaluationRollouts'
type MockStore_GetEvaluationRollouts_Call struct {
	*mock.Call
}

// GetEvaluationRollouts is a helper method to define mock.On call
//   - ctx context.Context
//   - flag storage.ResourceRequest
func (_e *MockStore_Expecter) GetEvaluationRollouts(ctx interface{}, flag interface{}) *MockStore_GetEvaluationRollouts_Call {
	return &MockStore_GetEvaluationRollouts_Call{Call: _e.mock.On("GetEvaluationRollouts", ctx, flag)}
}

func (_c *MockStore_GetEvaluationRollouts_Call) Run(run func(ctx context.Context, flag storage.ResourceRequest)) *MockStore_GetEvaluationRollouts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.ResourceRequest
		if args[1] != nil {
			arg1 = args[1].(storage.ResourceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetEvaluationRollouts_Call) Return(evaluationRollouts []*storage.EvaluationRollout, err error) *MockStore_GetEvaluationRollouts_Call {
	_c.Call.Return(evaluationRollouts, err)
	return _c
}

func (_c *MockStore_GetEvaluationRollouts_Call) RunAndReturn(run func(ctx context.Context, flag storage.ResourceRequest) ([]*storage.EvaluationRollout, error)) *MockStore_GetEvaluationRollouts_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvaluationRules provides a mock function for the type MockStore
func (_mock *MockStore) GetEvaluationRules(ctx context.Context, flag storage.ResourceRequest) ([]*storage.EvaluationRule, error) {
	ret := _mock.Called(ctx, flag)

	if len(ret) == 0 {
		panic("no return value specified for GetEvaluationRules")
	}

	var r0 []*storage.EvaluationRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ResourceRequest) ([]*storage.EvaluationRule, error)); ok {
		return returnFunc(ctx, flag)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ResourceRequest) []*storage.EvaluationRule); ok {
		r0 = returnFunc(ctx, flag)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.EvaluationRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.ResourceRequest) error); ok {
		r1 = returnFunc(ctx, flag)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetEvaluationRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvaluationRules'
type MockStore_GetEvaluationRules_Call struct {
	*mock.Call
}

// GetEvaluationRules is a helper method to define mock.On call
//   - ctx context.Context
//   - flag storage.ResourceRequest
func (_e *MockStore_Expecter) GetEvaluationRules(ctx interface{}, flag interface{}) *MockStore_GetEvaluationRules_Call {
	return &MockStore_GetEvaluationRules_Call{Call: _e.mock.On("GetEvaluationRules", ctx, flag)}
}

func (_c *MockStore_GetEvaluationRules_Call) Run(run func(ctx context.Context, flag storage.ResourceRequest)) *MockStore_GetEvaluationRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.ResourceRequest
		if args[1] != nil {
			arg1 = args[1].(storage.ResourceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetEvaluationRules_Call) Return(evaluationRules []*storage.EvaluationRule, err error) *MockStore_GetEvaluationRules_Call {
	_c.Call.Return(evaluationRules, err)
	return _c
}

func (_c *MockStore_GetEvaluationRules_Call) RunAndReturn(run func(ctx context.Context, flag storage.ResourceRequest) ([]*storage.EvaluationRule, error)) *MockStore_GetEvaluationRules_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlag provides a mock function for the type MockStore
func (_mock *MockStore) GetFlag(ctx context.Context, req storage.ResourceRequest) (*flipt.Flag, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetFlag")
	}

	var r0 *flipt.Flag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ResourceRequest) (*flipt.Flag, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ResourceRequest) *flipt.Flag); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Flag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.ResourceRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlag'
type MockStore_GetFlag_Call struct {
	*mock.Call
}

// GetFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - req storage.ResourceRequest
func (_e *MockStore_Expecter) GetFlag(ctx interface{}, req interface{}) *MockStore_GetFlag_Call {
	return &MockStore_GetFlag_Call{Call: _e.mock.On("GetFlag", ctx, req)}
}

func (_c *MockStore_GetFlag_Call) Run(run func(ctx context.Context, req storage.ResourceRequest)) *MockStore_GetFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.ResourceRequest
		if args[1] != nil {
			arg1 = args[1].(storage.ResourceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetFlag_Call) Return(flag *flipt.Flag, err error) *MockStore_GetFlag_Call {
	_c.Call.Return(flag, err)
	return _c
}

func (_c *MockStore_GetFlag_Call) RunAndReturn(run func(ctx context.Context, req storage.ResourceRequest) (*flipt.Flag, error)) *MockStore_GetFlag_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamespace provides a mock function for the type MockStore
func (_mock *MockStore) GetNamespace(ctx context.Context, ns storage.NamespaceRequest) (*flipt.Namespace, error) {
	ret := _mock.Called(ctx, ns)

	if len(ret) == 0 {
		panic("no return value specified for GetNamespace")
	}

	var r0 *flipt.Namespace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.NamespaceRequest) (*flipt.Namespace, error)); ok {
		return returnFunc(ctx, ns)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.NamespaceRequest) *flipt.Namespace); ok {
		r0 = returnFunc(ctx, ns)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Namespace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.NamespaceRequest) error); ok {
		r1 = returnFunc(ctx, ns)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespace'
type MockStore_GetNamespace_Call struct {
	*mock.Call
}

// GetNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - ns storage.NamespaceRequest
func (_e *MockStore_Expecter) GetNamespace(ctx interface{}, ns interface{}) *MockStore_GetNamespace_Call {
	return &MockStore_GetNamespace_Call{Call: _e.mock.On("GetNamespace", ctx, ns)}
}

func (_c *MockStore_GetNamespace_Call) Run(run func(ctx context.Context, ns storage.NamespaceRequest)) *MockStore_GetNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.NamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(storage.NamespaceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetNamespace_Call) Return(namespace *flipt.Namespace, err error) *MockStore_GetNamespace_Call {
	_c.Call.Return(namespace, err)
	return _c
}

func (_c *MockStore_GetNamespace_Call) RunAndReturn(run func(ctx context.Context, ns storage.NamespaceRequest) (*flipt.Namespace, error)) *MockStore_GetNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// GetRollout provides a mock function for the type MockStore
func (_mock *MockStore) GetRollout(ctx context.Context, ns storage.NamespaceRequest, id string) (*flipt.Rollout, error) {
	ret := _mock.Called(ctx, ns, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRollout")
	}

	var r0 *flipt.Rollout
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.NamespaceRequest, string) (*flipt.Rollout, error)); ok {
		return returnFunc(ctx, ns, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.NamespaceRequest, string) *flipt.Rollout); ok {
		r0 = returnFunc(ctx, ns, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Rollout)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.NamespaceRequest, string) error); ok {
		r1 = returnFunc(ctx, ns, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetRollout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRollout'
type MockStore_GetRollout_Call struct {
	*mock.Call
}

// GetRollout is a helper method to define mock.On call
//   - ctx context.Context
//   - ns storage.NamespaceRequest
//   - id string
func (_e *MockStore_Expecter) GetRollout(ctx interface{}, ns interface{}, id interface{}) *MockStore_GetRollout_Call {
	return &MockStore_GetRollout_Call{Call: _e.mock.On("GetRollout", ctx, ns, id)}
}

func (_c *MockStore_GetRollout_Call) Run(run func(ctx context.Context, ns storage.NamespaceRequest, id string)) *MockStore_GetRollout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.NamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(storage.NamespaceRequest)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_GetRollout_Call) Return(rollout *flipt.Rollout, err error) *MockStore_GetRollout_Call {
	_c.Call.Return(rollout, err)
	return _c
}

func (_c *MockStore_GetRollout_Call) RunAndReturn(run func(ctx context.Context, ns storage.NamespaceRequest, id string) (*flipt.Rollout, error)) *MockStore_GetRollout_Call {
	_c.Call.Return(run)
	return _c
}

// GetRule provides a mock function for the type MockStore
func (_mock *MockStore) GetRule(ctx context.Context, ns storage.NamespaceRequest, id string) (*flipt.Rule, error) {
	ret := _mock.Called(ctx, ns, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRule")
	}

	var r0 *flipt.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.NamespaceRequest, string) (*flipt.Rule, error)); ok {
		return returnFunc(ctx, ns, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.NamespaceRequest, string) *flipt.Rule); ok {
		r0 = returnFunc(ctx, ns, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Rule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.NamespaceRequest, string) error); ok {
		r1 = returnFunc(ctx, ns, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRule'
type MockStore_GetRule_Call struct {
	*mock.Call
}

// GetRule is a helper method to define mock.On call
//   - ctx context.Context
//   - ns storage.NamespaceRequest
//   - id string
func (_e *MockStore_Expecter) GetRule(ctx interface{}, ns interface{}, id interface{}) *MockStore_GetRule_Call {
	return &MockStore_GetRule_Call{Call: _e.mock.On("GetRule", ctx, ns, id)}
}

func (_c *MockStore_GetRule_Call) Run(run func(ctx context.Context, ns storage.NamespaceRequest, id string)) *MockStore_GetRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.NamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(storage.NamespaceRequest)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_GetRule_Call) Return(rule *flipt.Rule, err error) *MockStore_GetRule_Call {
	_c.Call.Return(rule, err)
	return _c
}

func (_c *MockStore_GetRule_Call) RunAndReturn(run func(ctx context.Context, ns storage.NamespaceRequest, id string) (*flipt.Rule, error)) *MockStore_GetRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetSegment provides a mock function for the type MockStore
func (_mock *MockStore) GetSegment(ctx context.Context, req storage.ResourceRequest) (*flipt.Segment, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetSegment")
	}

	var r0 *flipt.Segment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ResourceRequest) (*flipt.Segment, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.ResourceRequest) *flipt.Segment); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Segment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.ResourceRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetSegment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSegment'
type MockStore_GetSegment_Call struct {
	*mock.Call
}

// GetSegment is a helper method to define mock.On call
//   - ctx context.Context
//   - req storage.ResourceRequest
func (_e *MockStore_Expecter) GetSegment(ctx interface{}, req interface{}) *MockStore_GetSegment_Call {
	return &MockStore_GetSegment_Call{Call: _e.mock.On("GetSegment", ctx, req)}
}

func (_c *MockStore_GetSegment_Call) Run(run func(ctx context.Context, req storage.ResourceRequest)) *MockStore_GetSegment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.ResourceRequest
		if args[1] != nil {
			arg1 = args[1].(storage.ResourceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetSegment_Call) Return(segment *flipt.Segment, err error) *MockStore_GetSegment_Call {
	_c.Call.Return(segment, err)
	return _c
}

func (_c *MockStore_GetSegment_Call) RunAndReturn(run func(ctx context.Context, req storage.ResourceRequest) (*flipt.Segment, error)) *MockStore_GetSegment_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function for the type MockStore
func (_mock *MockStore) GetVersion(ctx context.Context, ns storage.NamespaceRequest) (string, error) {
	ret := _mock.Called(ctx, ns)

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.NamespaceRequest) (string, error)); ok {
		return returnFunc(ctx, ns)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.NamespaceRequest) string); ok {
		r0 = returnFunc(ctx, ns)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.NamespaceRequest) error); ok {
		r1 = returnFunc(ctx, ns)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockStore_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - ns storage.NamespaceRequest
func (_e *MockStore_Expecter) GetVersion(ctx interface{}, ns interface{}) *MockStore_GetVersion_Call {
	return &MockStore_GetVersion_Call{Call: _e.mock.On("GetVersion", ctx, ns)}
}

func (_c *MockStore_GetVersion_Call) Run(run func(ctx context.Context, ns storage.NamespaceRequest)) *MockStore_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.NamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(storage.NamespaceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetVersion_Call) Return(s string, err error) *MockStore_GetVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockStore_GetVersion_Call) RunAndReturn(run func(ctx context.Context, ns storage.NamespaceRequest) (string, error)) *MockStore_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// ListFlags provides a mock function for the type MockStore
func (_mock *MockStore) ListFlags(ctx context.Context, req *storage.ListRequest[storage.NamespaceRequest]) (storage.ResultSet[*flipt.Flag], error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListFlags")
	}

	var r0 storage.ResultSet[*flipt.Flag]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.ListRequest[storage.NamespaceRequest]) (storage.ResultSet[*flipt.Flag], error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.ListRequest[storage.NamespaceRequest]) storage.ResultSet[*flipt.Flag]); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(storage.ResultSet[*flipt.Flag])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *storage.ListRequest[storage.NamespaceRequest]) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListFlags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFlags'
type MockStore_ListFlags_Call struct {
	*mock.Call
}

// ListFlags is a helper method to define mock.On call
//   - ctx context.Context
//   - req *storage.ListRequest[storage.NamespaceRequest]
func (_e *MockStore_Expecter) ListFlags(ctx interface{}, req interface{}) *MockStore_ListFlags_Call {
	return &MockStore_ListFlags_Call{Call: _e.mock.On("ListFlags", ctx, req)}
}

func (_c *MockStore_ListFlags_Call) Run(run func(ctx context.Context, req *storage.ListRequest[storage.NamespaceRequest])) *MockStore_ListFlags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *storage.ListRequest[storage.NamespaceRequest]
		if args[1] != nil {
			arg1 = args[1].(*storage.ListRequest[storage.NamespaceRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListFlags_Call) Return(resultSet storage.ResultSet[*flipt.Flag], err error) *MockStore_ListFlags_Call {
	_c.Call.Return(resultSet, err)
	return _c
}

func (_c *MockStore_ListFlags_Call) RunAndReturn(run func(ctx context.Context, req *storage.ListRequest[storage.NamespaceRequest]) (storage.ResultSet[*flipt.Flag], error)) *MockStore_ListFlags_Call {
	_c.Call.Return(run)
	return _c
}

// ListNamespaces provides a mock function for the type MockStore
func (_mock *MockStore) ListNamespaces(ctx context.Context, req *storage.ListRequest[storage.ReferenceRequest]) (storage.ResultSet[*flipt.Namespace], error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListNamespaces")
	}

	var r0 storage.ResultSet[*flipt.Namespace]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.ListRequest[storage.ReferenceRequest]) (storage.ResultSet[*flipt.Namespace], error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.ListRequest[storage.ReferenceRequest]) storage.ResultSet[*flipt.Namespace]); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(storage.ResultSet[*flipt.Namespace])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *storage.ListRequest[storage.ReferenceRequest]) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListNamespaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNamespaces'
type MockStore_ListNamespaces_Call struct {
	*mock.Call
}

// ListNamespaces is a helper method to define mock.On call
//   - ctx context.Context
//   - req *storage.ListRequest[storage.ReferenceRequest]
func (_e *MockStore_Expecter) ListNamespaces(ctx interface{}, req interface{}) *MockStore_ListNamespaces_Call {
	return &MockStore_ListNamespaces_Call{Call: _e.mock.On("ListNamespaces", ctx, req)}
}

func (_c *MockStore_ListNamespaces_Call) Run(run func(ctx context.Context, req *storage.ListRequest[storage.ReferenceRequest])) *MockStore_ListNamespaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *storage.ListRequest[storage.ReferenceRequest]
		if args[1] != nil {
			arg1 = args[1].(*storage.ListRequest[storage.ReferenceRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListNamespaces_Call) Return(resultSet storage.ResultSet[*flipt.Namespace], err error) *MockStore_ListNamespaces_Call {
	_c.Call.Return(resultSet, err)
	return _c
}

func (_c *MockStore_ListNamespaces_Call) RunAndReturn(run func(ctx context.Context, req *storage.ListRequest[storage.ReferenceRequest]) (storage.ResultSet[*flipt.Namespace], error)) *MockStore_ListNamespaces_Call {
	_c.Call.Return(run)
	return _c
}

// ListRollouts provides a mock function for the type MockStore
func (_mock *MockStore) ListRollouts(ctx context.Context, req *storage.ListRequest[storage.ResourceRequest]) (storage.ResultSet[*flipt.Rollout], error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListRollouts")
	}

	var r0 storage.ResultSet[*flipt.Rollout]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.ListRequest[storage.ResourceRequest]) (storage.ResultSet[*flipt.Rollout], error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.ListRequest[storage.ResourceRequest]) storage.ResultSet[*flipt.Rollout]); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(storage.ResultSet[*flipt.Rollout])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *storage.ListRequest[storage.ResourceRequest]) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListRollouts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRollouts'
type MockStore_ListRollouts_Call struct {
	*mock.Call
}

// ListRollouts is a helper method to define mock.On call
//   - ctx context.Context
//   - req *storage.ListRequest[storage.ResourceRequest]
func (_e *MockStore_Expecter) ListRollouts(ctx interface{}, req interface{}) *MockStore_ListRollouts_Call {
	return &MockStore_ListRollouts_Call{Call: _e.mock.On("ListRollouts", ctx, req)}
}

func (_c *MockStore_ListRollouts_Call) Run(run func(ctx context.Context, req *storage.ListRequest[storage.ResourceRequest])) *MockStore_ListRollouts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *storage.ListRequest[storage.ResourceRequest]
		if args[1] != nil {
			arg1 = args[1].(*storage.ListRequest[storage.ResourceRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListRollouts_Call) Return(resultSet storage.ResultSet[*flipt.Rollout], err error) *MockStore_ListRollouts_Call {
	_c.Call.Return(resultSet, err)
	return _c
}

func (_c *MockStore_ListRollouts_Call) RunAndReturn(run func(ctx context.Context, req *storage.ListRequest[storage.ResourceRequest]) (storage.ResultSet[*flipt.Rollout], error)) *MockStore_ListRollouts_Call {
	_c.Call.Return(run)
	return _c
}

// ListRules provides a mock function for the type MockStore
func (_mock *MockStore) ListRules(ctx context.Context, req *storage.ListRequest[storage.ResourceRequest]) (storage.ResultSet[*flipt.Rule], error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListRules")
	}

	var r0 storage.ResultSet[*flipt.Rule]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.ListRequest[storage.ResourceRequest]) (storage.ResultSet[*flipt.Rule], error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.ListRequest[storage.ResourceRequest]) storage.ResultSet[*flipt.Rule]); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(storage.ResultSet[*flipt.Rule])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *storage.ListRequest[storage.ResourceRequest]) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRules'
type MockStore_ListRules_Call struct {
	*mock.Call
}

// ListRules is a helper method to define mock.On call
//   - ctx context.Context
//   - req *storage.ListRequest[storage.ResourceRequest]
func (_e *MockStore_Expecter) ListRules(ctx interface{}, req interface{}) *MockStore_ListRules_Call {
	return &MockStore_ListRules_Call{Call: _e.mock.On("ListRules", ctx, req)}
}

func (_c *MockStore_ListRules_Call) Run(run func(ctx context.Context, req *storage.ListRequest[storage.ResourceRequest])) *MockStore_ListRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *storage.ListRequest[storage.ResourceRequest]
		if args[1] != nil {
			arg1 = args[1].(*storage.ListRequest[storage.ResourceRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListRules_Call) Return(resultSet storage.ResultSet[*flipt.Rule], err error) *MockStore_ListRules_Call {
	_c.Call.Return(resultSet, err)
	return _c
}

func (_c *MockStore_ListRules_Call) RunAndReturn(run func(ctx context.Context, req *storage.ListRequest[storage.ResourceRequest]) (storage.ResultSet[*flipt.Rule], error)) *MockStore_ListRules_Call {
	_c.Call.Return(run)
	return _c
}

// ListSegments provides a mock function for the type MockStore
func (_mock *MockStore) ListSegments(ctx context.Context, req *storage.ListRequest[storage.NamespaceRequest]) (storage.ResultSet[*flipt.Segment], error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListSegments")
	}

	var r0 storage.ResultSet[*flipt.Segment]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.ListRequest[storage.NamespaceRequest]) (storage.ResultSet[*flipt.Segment], error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.ListRequest[storage.NamespaceRequest]) storage.ResultSet[*flipt.Segment]); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(storage.ResultSet[*flipt.Segment])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *storage.ListRequest[storage.NamespaceRequest]) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListSegments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSegments'
type MockStore_ListSegments_Call struct {
	*mock.Call
}

// ListSegments is a helper method to define mock.On call
//   - ctx context.Context
//   - req *storage.ListRequest[storage.NamespaceRequest]
func (_e *MockStore_Expecter) ListSegments(ctx interface{}, req interface{}) *MockStore_ListSegments_Call {
	return &MockStore_ListSegments_Call{Call: _e.mock.On("ListSegments", ctx, req)}
}

func (_c *MockStore_ListSegments_Call) Run(run func(ctx context.Context, req *storage.ListRequest[storage.NamespaceRequest])) *MockStore_ListSegments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *storage.ListRequest[storage.NamespaceRequest]
		if args[1] != nil {
			arg1 = args[1].(*storage.ListRequest[storage.NamespaceRequest])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListSegments_Call) Return(resultSet storage.ResultSet[*flipt.Segment], err error) *MockStore_ListSegments_Call {
	_c.Call.Return(resultSet, err)
	return _c
}

func (_c *MockStore_ListSegments_Call) RunAndReturn(run func(ctx context.Context, req *storage.ListRequest[storage.NamespaceRequest]) (storage.ResultSet[*flipt.Segment], error)) *MockStore_ListSegments_Call {
	_c.Call.Return(run)
	return _c
}

// OrderRollouts provides a mock function for the type MockStore
func (_mock *MockStore) OrderRollouts(ctx context.Context, r *flipt.OrderRolloutsRequest) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for OrderRollouts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.OrderRolloutsRequest) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_OrderRollouts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderRollouts'
type MockStore_OrderRollouts_Call struct {
	*mock.Call
}

// OrderRollouts is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.OrderRolloutsRequest
func (_e *MockStore_Expecter) OrderRollouts(ctx interface{}, r interface{}) *MockStore_OrderRollouts_Call {
	return &MockStore_OrderRollouts_Call{Call: _e.mock.On("OrderRollouts", ctx, r)}
}

func (_c *MockStore_OrderRollouts_Call) Run(run func(ctx context.Context, r *flipt.OrderRolloutsRequest)) *MockStore_OrderRollouts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.OrderRolloutsRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.OrderRolloutsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_OrderRollouts_Call) Return(err error) *MockStore_OrderRollouts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_OrderRollouts_Call) RunAndReturn(run func(ctx context.Context, r *flipt.OrderRolloutsRequest) error) *MockStore_OrderRollouts_Call {
	_c.Call.Return(run)
	return _c
}

// OrderRules provides a mock function for the type MockStore
func (_mock *MockStore) OrderRules(ctx context.Context, r *flipt.OrderRulesRequest) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for OrderRules")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.OrderRulesRequest) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_OrderRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderRules'
type MockStore_OrderRules_Call struct {
	*mock.Call
}

// OrderRules is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.OrderRulesRequest
func (_e *MockStore_Expecter) OrderRules(ctx interface{}, r interface{}) *MockStore_OrderRules_Call {
	return &MockStore_OrderRules_Call{Call: _e.mock.On("OrderRules", ctx, r)}
}

func (_c *MockStore_OrderRules_Call) Run(run func(ctx context.Context, r *flipt.OrderRulesRequest)) *MockStore_OrderRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.OrderRulesRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.OrderRulesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_OrderRules_Call) Return(err error) *MockStore_OrderRules_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_OrderRules_Call) RunAndReturn(run func(ctx context.Context, r *flipt.OrderRulesRequest) error) *MockStore_OrderRules_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockStore
func (_mock *MockStore) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStore_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockStore_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockStore_Expecter) String() *MockStore_String_Call {
	return &MockStore_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockStore_String_Call) Run(run func()) *MockStore_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_String_Call) Return(s string) *MockStore_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStore_String_Call) RunAndReturn(run func() string) *MockStore_String_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConstraint provides a mock function for the type MockStore
func (_mock *MockStore) UpdateConstraint(ctx context.Context, r *flipt.UpdateConstraintRequest) (*flipt.Constraint, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConstraint")
	}

	var r0 *flipt.Constraint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateConstraintRequest) (*flipt.Constraint, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateConstraintRequest) *flipt.Constraint); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Constraint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.UpdateConstraintRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateConstraint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConstraint'
type MockStore_UpdateConstraint_Call struct {
	*mock.Call
}

// UpdateConstraint is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.UpdateConstraintRequest
func (_e *MockStore_Expecter) UpdateConstraint(ctx interface{}, r interface{}) *MockStore_UpdateConstraint_Call {
	return &MockStore_UpdateConstraint_Call{Call: _e.mock.On("UpdateConstraint", ctx, r)}
}

func (_c *MockStore_UpdateConstraint_Call) Run(run func(ctx context.Context, r *flipt.UpdateConstraintRequest)) *MockStore_UpdateConstraint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.UpdateConstraintRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.UpdateConstraintRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_UpdateConstraint_Call) Return(constraint *flipt.Constraint, err error) *MockStore_UpdateConstraint_Call {
	_c.Call.Return(constraint, err)
	return _c
}

func (_c *MockStore_UpdateConstraint_Call) RunAndReturn(run func(ctx context.Context, r *flipt.UpdateConstraintRequest) (*flipt.Constraint, error)) *MockStore_UpdateConstraint_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDistribution provides a mock function for the type MockStore
func (_mock *MockStore) UpdateDistribution(ctx context.Context, r *flipt.UpdateDistributionRequest) (*flipt.Distribution, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDistribution")
	}

	var r0 *flipt.Distribution
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateDistributionRequest) (*flipt.Distribution, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateDistributionRequest) *flipt.Distribution); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Distribution)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.UpdateDistributionRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDistribution'
type MockStore_UpdateDistribution_Call struct {
	*mock.Call
}

// UpdateDistribution is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.UpdateDistributionRequest
func (_e *MockStore_Expecter) UpdateDistribution(ctx interface{}, r interface{}) *MockStore_UpdateDistribution_Call {
	return &MockStore_UpdateDistribution_Call{Call: _e.mock.On("UpdateDistribution", ctx, r)}
}

func (_c *MockStore_UpdateDistribution_Call) Run(run func(ctx context.Context, r *flipt.UpdateDistributionRequest)) *MockStore_UpdateDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.UpdateDistributionRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.UpdateDistributionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_UpdateDistribution_Call) Return(distribution *flipt.Distribution, err error) *MockStore_UpdateDistribution_Call {
	_c.Call.Return(distribution, err)
	return _c
}

func (_c *MockStore_UpdateDistribution_Call) RunAndReturn(run func(ctx context.Context, r *flipt.UpdateDistributionRequest) (*flipt.Distribution, error)) *MockStore_UpdateDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFlag provides a mock function for the type MockStore
func (_mock *MockStore) UpdateFlag(ctx context.Context, r *flipt.UpdateFlagRequest) (*flipt.Flag, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFlag")
	}

	var r0 *flipt.Flag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateFlagRequest) (*flipt.Flag, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateFlagRequest) *flipt.Flag); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Flag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.UpdateFlagRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFlag'
type MockStore_UpdateFlag_Call struct {
	*mock.Call
}

// UpdateFlag is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.UpdateFlagRequest
func (_e *MockStore_Expecter) UpdateFlag(ctx interface{}, r interface{}) *MockStore_UpdateFlag_Call {
	return &MockStore_UpdateFlag_Call{Call: _e.mock.On("UpdateFlag", ctx, r)}
}

func (_c *MockStore_UpdateFlag_Call) Run(run func(ctx context.Context, r *flipt.UpdateFlagRequest)) *MockStore_UpdateFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.UpdateFlagRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.UpdateFlagRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_UpdateFlag_Call) Return(flag *flipt.Flag, err error) *MockStore_UpdateFlag_Call {
	_c.Call.Return(flag, err)
	return _c
}

func (_c *MockStore_UpdateFlag_Call) RunAndReturn(run func(ctx context.Context, r *flipt.UpdateFlagRequest) (*flipt.Flag, error)) *MockStore_UpdateFlag_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNamespace provides a mock function for the type MockStore
func (_mock *MockStore) UpdateNamespace(ctx context.Context, r *flipt.UpdateNamespaceRequest) (*flipt.Namespace, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNamespace")
	}

	var r0 *flipt.Namespace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateNamespaceRequest) (*flipt.Namespace, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateNamespaceRequest) *flipt.Namespace); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Namespace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.UpdateNamespaceRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNamespace'
type MockStore_UpdateNamespace_Call struct {
	*mock.Call
}

// UpdateNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.UpdateNamespaceRequest
func (_e *MockStore_Expecter) UpdateNamespace(ctx interface{}, r interface{}) *MockStore_UpdateNamespace_Call {
	return &MockStore_UpdateNamespace_Call{Call: _e.mock.On("UpdateNamespace", ctx, r)}
}

func (_c *MockStore_UpdateNamespace_Call) Run(run func(ctx context.Context, r *flipt.UpdateNamespaceRequest)) *MockStore_UpdateNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.UpdateNamespaceRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.UpdateNamespaceRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_UpdateNamespace_Call) Return(namespace *flipt.Namespace, err error) *MockStore_UpdateNamespace_Call {
	_c.Call.Return(namespace, err)
	return _c
}

func (_c *MockStore_UpdateNamespace_Call) RunAndReturn(run func(ctx context.Context, r *flipt.UpdateNamespaceRequest) (*flipt.Namespace, error)) *MockStore_UpdateNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRollout provides a mock function for the type MockStore
func (_mock *MockStore) UpdateRollout(ctx context.Context, r *flipt.UpdateRolloutRequest) (*flipt.Rollout, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRollout")
	}

	var r0 *flipt.Rollout
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateRolloutRequest) (*flipt.Rollout, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateRolloutRequest) *flipt.Rollout); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Rollout)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.UpdateRolloutRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateRollout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRollout'
type MockStore_UpdateRollout_Call struct {
	*mock.Call
}

// UpdateRollout is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.UpdateRolloutRequest
func (_e *MockStore_Expecter) UpdateRollout(ctx interface{}, r interface{}) *MockStore_UpdateRollout_Call {
	return &MockStore_UpdateRollout_Call{Call: _e.mock.On("UpdateRollout", ctx, r)}
}

func (_c *MockStore_UpdateRollout_Call) Run(run func(ctx context.Context, r *flipt.UpdateRolloutRequest)) *MockStore_UpdateRollout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.UpdateRolloutRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.UpdateRolloutRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_UpdateRollout_Call) Return(rollout *flipt.Rollout, err error) *MockStore_UpdateRollout_Call {
	_c.Call.Return(rollout, err)
	return _c
}

func (_c *MockStore_UpdateRollout_Call) RunAndReturn(run func(ctx context.Context, r *flipt.UpdateRolloutRequest) (*flipt.Rollout, error)) *MockStore_UpdateRollout_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRule provides a mock function for the type MockStore
func (_mock *MockStore) UpdateRule(ctx context.Context, r *flipt.UpdateRuleRequest) (*flipt.Rule, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRule")
	}

	var r0 *flipt.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateRuleRequest) (*flipt.Rule, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateRuleRequest) *flipt.Rule); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Rule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.UpdateRuleRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRule'
type MockStore_UpdateRule_Call struct {
	*mock.Call
}

// UpdateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.UpdateRuleRequest
func (_e *MockStore_Expecter) UpdateRule(ctx interface{}, r interface{}) *MockStore_UpdateRule_Call {
	return &MockStore_UpdateRule_Call{Call: _e.mock.On("UpdateRule", ctx, r)}
}

func (_c *MockStore_UpdateRule_Call) Run(run func(ctx context.Context, r *flipt.UpdateRuleRequest)) *MockStore_UpdateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.UpdateRuleRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.UpdateRuleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_UpdateRule_Call) Return(rule *flipt.Rule, err error) *MockStore_UpdateRule_Call {
	_c.Call.Return(rule, err)
	return _c
}

func (_c *MockStore_UpdateRule_Call) RunAndReturn(run func(ctx context.Context, r *flipt.UpdateRuleRequest) (*flipt.Rule, error)) *MockStore_UpdateRule_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSegment provides a mock function for the type MockStore
func (_mock *MockStore) UpdateSegment(ctx context.Context, r *flipt.UpdateSegmentRequest) (*flipt.Segment, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSegment")
	}

	var r0 *flipt.Segment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateSegmentRequest) (*flipt.Segment, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateSegmentRequest) *flipt.Segment); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Segment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.UpdateSegmentRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateSegment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSegment'
type MockStore_UpdateSegment_Call struct {
	*mock.Call
}

// UpdateSegment is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.UpdateSegmentRequest
func (_e *MockStore_Expecter) UpdateSegment(ctx interface{}, r interface{}) *MockStore_UpdateSegment_Call {
	return &MockStore_UpdateSegment_Call{Call: _e.mock.On("UpdateSegment", ctx, r)}
}

func (_c *MockStore_UpdateSegment_Call) Run(run func(ctx context.Context, r *flipt.UpdateSegmentRequest)) *MockStore_UpdateSegment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.UpdateSegmentRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.UpdateSegmentRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_UpdateSegment_Call) Return(segment *flipt.Segment, err error) *MockStore_UpdateSegment_Call {
	_c.Call.Return(segment, err)
	return _c
}

func (_c *MockStore_UpdateSegment_Call) RunAndReturn(run func(ctx context.Context, r *flipt.UpdateSegmentRequest) (*flipt.Segment, error)) *MockStore_UpdateSegment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVariant provides a mock function for the type MockStore
func (_mock *MockStore) UpdateVariant(ctx context.Context, r *flipt.UpdateVariantRequest) (*flipt.Variant, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVariant")
	}

	var r0 *flipt.Variant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateVariantRequest) (*flipt.Variant, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *flipt.UpdateVariantRequest) *flipt.Variant); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*flipt.Variant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *flipt.UpdateVariantRequest) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateVariant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVariant'
type MockStore_UpdateVariant_Call struct {
	*mock.Call
}

// UpdateVariant is a helper method to define mock.On call
//   - ctx context.Context
//   - r *flipt.UpdateVariantRequest
func (_e *MockStore_Expecter) UpdateVariant(ctx interface{}, r interface{}) *MockStore_UpdateVariant_Call {
	return &MockStore_UpdateVariant_Call{Call: _e.mock.On("UpdateVariant", ctx, r)}
}

func (_c *MockStore_UpdateVariant_Call) Run(run func(ctx context.Context, r *flipt.UpdateVariantRequest)) *MockStore_UpdateVariant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *flipt.UpdateVariantRequest
		if args[1] != nil {
			arg1 = args[1].(*flipt.UpdateVariantRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_UpdateVariant_Call) Return(variant *flipt.Variant, err error) *MockStore_UpdateVariant_Call {
	_c.Call.Return(variant, err)
	return _c
}

func (_c *MockStore_UpdateVariant_Call) RunAndReturn(run func(ctx context.Context, r *flipt.UpdateVariantRequest) (*flipt.Variant, error)) *MockStore_UpdateVariant_Call {
	_c.Call.Return(run)
	return _c
}
