version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - flipt_network

  flipt:
    image: flipt/flipt:latest
    command: ["./flipt", "--force-migrate"]
    depends_on:
      - prometheus
    ports:
      - "8080:8080"
    networks:
      - flipt_network
    environment:
      - FLIPT_LOG_LEVEL=debug
      - FLIPT_CACHE_ENABLED=true
      - FLIPT_CACHE_BACKEND=memory
      - FLIPT_CACHE_TTL=1m
      - FLIPT_META_TELEMETRY_ENABLED=false
      
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          access: proxy 
          orgId: 1
          url: http://prometheus:9090
          uid: prometheus
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - flipt_network

networks:
  flipt_network:
