name: Benchmarks
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  benchmark:
    name: Benchmark SQLite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup

      - name: Run Benchmarks
        run: go test -run XXX -bench . -benchtime 5s -benchmem -short ./...
