name: Buf
on:
  pull_request:
    paths-ignore:
      - "*.md"
      - ".all-contributorsrc"

jobs:
  lint:
    name: Lint/Breaking
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: bufbuild/buf-setup-action@v1.0.0
        with:
          version: "latest"

      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "rpc/flipt"

      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: "rpc/flipt"
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=master"
