name: Buf
on:
  push:
    branches:
      - main
    paths-ignore:
      - "deploy/**"
      - "examples/**"
      - "logos/**"
      - "**.md"
      - "**.txt"
      - "**.ya?ml"
  pull_request:
    paths-ignore:
      - "deploy/**"
      - "examples/**"
      - "logos/**"
      - "**.md"
      - "**.txt"
      - "**.ya?ml"

jobs:
  lint:
    name: Lint/Breaking
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: bufbuild/buf-setup-action@v1.6.0
        with:
          version: "latest"

      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "rpc/flipt"

      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: "rpc/flipt"
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main"
