name: DevContainer
on:
  push:
    branches:
      - v2
    paths:
      - ".devcontainer/**"
  pull_request:
    paths:
      - ".devcontainer/**"
  workflow_dispatch:

jobs:
  build:
    name: "Build DevContainer"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: mise --version && go version && node --version
