name: Publish Docs On Release
on:
  release:
    type: created
jobs:

  publish:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@master

    - name: Publish Docs
      uses: ./build/actions/publish-docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
