name: Docs
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:

  ## Publish Docs
  publish:
    name: Publish Docs
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Publish
      uses: ./.github/actions/publish-docs
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
