on:
  release:
    type: created
name: Publish Docs On Release
jobs:
  publish:
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish Docs
      uses: ./build/actions/publish-docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
