name: Integration Tests Experiment
on:
  push:
    branches:
      - main
    paths-ignore:
      - "examples/**"
      - "logos/**"
      - "**.md"
      - "**.txt"
  pull_request:
    paths-ignore:
      - "examples/**"
      - "logos/**"
      - "**.md"
      - "**.txt"
  workflow_dispatch:

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true
          cache: true

      - uses: magefile/mage-action@v2
        with:
          version: latest
          args: test:integration
          workdir: hack/build

      - name: Upload Flipt Service Logs
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: Flipt Service Logs
          path: hack/build/logs
          retention-days: 5

