name: Lint
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  go-lint:
    name: "Lint Go"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup

      - name: golangci-lint
        run: golangci-lint run --timeout=10m

  ui-lint:
    name: "Lint UI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup

      - name: Lint
        run: |
          npm ci
          npm run lint
        working-directory: ui

  go-mod-tidy:
    name: "Go Mod Tidy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup

      - name: Run go mod tidy.
        run: go mod tidy

      - name: Ensure clean git state.
        run: git diff-index --quiet HEAD -- || (echo "Please run 'go mod tidy' and commit changes." && exit 1)
