name: Go Nancy
on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "*.yml"
      - ".all-contributorsrc"

jobs:
  sleuth:
    name: Sleuth
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.x"

      - run: go list -json -m all > go.list

      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main
