name: Create Documentation Issue

on:
  pull_request:
    types: [labeled]
    branches:
      - main

jobs:
  create-issue:
    if: github.event.label.name == 'needs docs'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.FLIPT_RELEASE_BOT_APP_ID }}
          private_key: ${{ secrets.FLIPT_RELEASE_BOT_APP_PEM }}
          installation_id: ${{ secrets.FLIPT_RELEASE_BOT_INSTALLATION_ID }}

      - name: Create documentation issue
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          pr_title=$(jq -r .pull_request.title < $GITHUB_EVENT_PATH)
          pr_url=$(jq -r .pull_request.html_url < $GITHUB_EVENT_PATH)
          issue_title="Document: $pr_title"
          issue_body="This issue was created to document the following pull request: $pr_url"
          gh issue create --title "$issue_title" --body "$issue_body" --repo ${{ github.repository_owner }}/docs
