name: Proto Push
on:
  push:
    tags:
      - "v2*"

jobs:
  proto-push:
    name: "Push Protos"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: bufbuild/buf-action@v1
        with:
          input: "rpc/v2"
          lint: true

      - uses: bufbuild/buf-action@v1
        with:
          input: "rpc/v2"
          breaking: true
          breaking_against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=v2"

      - uses: bufbuild/buf-action@v1
        with:
          input: "rpc/v2"
          push: true
          token: ${{ secrets.BUF_TOKEN }}
