name: Scan
on:
  push:
    branches:
      - main
    paths-ignore:
      - "deploy/**"
      - "examples/**"
      - "logos/**"
      - "**.md"
      - "**.txt"
      - "**.ya?ml"
  pull_request:
    paths-ignore:
      - "deploy/**"
      - "examples/**"
      - "logos/**"
      - "**.md"
      - "**.txt"
      - "**.ya?ml"
  workflow_dispatch:

jobs:
  sleuth:
    name: Sleuth
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "1.17.x"

      - run: go list -json -m all > go.list

      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main

  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
