name: Build PR Image

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  build:
    name: Build and Push `flipt`
    runs-on: ubuntu-latest
    if: ${{ github.triggering_actor != 'dependabot[bot]' && (github.event_name != 'pull_request' || github.event.action != 'closed') }}
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate UUID image name
        id: uuid
        run: echo "UUID_FLIPT=flipt-$(uuidgen --time)" >> $GITHUB_ENV

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # An anonymous, emphemeral registry built on ttl.sh
          images: registry.uffizzi.com/${{ env.UUID_FLIPT }}
          tags: type=raw,value=24h

      - name: Build and Push Image to Uffizzi Ephemeral Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: .
          file: ./build/Dockerfile.uffizzi
          cache-from: type=gha
          cache-to: type=gha,mode=max

  render-compose-file:
    name: Render Docker Compose File
    # Pass output of this workflow to another triggered by `workflow_run` event.
    runs-on: ubuntu-latest
    if: ${{ github.triggering_actor != 'dependabot[bot]' && github.event.action != 'closed' }}
    needs:
      - build
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Render Compose File
        run: |
          FLIPT_IMAGE=$(echo ${{ needs.build.outputs.tags }})
          export FLIPT_IMAGE
          # Render simple template from environment variables.
          envsubst < ./build/docker-compose.uffizzi.yml > docker-compose.rendered.yml
          cat docker-compose.rendered.yml

      - name: Upload Rendered Compose File as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-spec-compose
          path: docker-compose.rendered.yml
          retention-days: 2

      - name: Upload PR Event as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-spec-event
          path: ${{ github.event_path }}
          retention-days: 2

  delete-preview:
    name: Delete Existing Preview
    runs-on: ubuntu-latest
    if: ${{ github.triggering_actor != 'dependabot[bot]' && github.event.action == 'closed' }}
    steps:
      # If this PR is closing, we will not render a compose file nor pass it to the next workflow.
      - name: Upload PR Event as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-spec
          path: ${{ github.event_path }}
          retention-days: 2
