on:
  workflow_dispatch:
    inputs:
      tag:
        description: Flipt release version tag to generate
        required: true

name: Update gRPC Client Repositories
jobs:
  clients:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.FLIPT_RELEASE_BOT_APP_ID }}
          private_key: ${{ secrets.FLIPT_RELEASE_BOT_APP_PEM }}
          installation_id: ${{ secrets.FLIPT_RELEASE_BOT_INSTALLATION_ID }}
      - name: Trigger Workflow
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh workflow run proto-update.yml -f tag="${{ inputs.tag }}"
